### ISSUE TITLE
Expose network status change

### ISSUE THREAD

**Issue by kingsleyzissou** [aerogear/offix#1069]
## Feature Request

I would like to expose the network status indicator used in the datastore, I just wanted to start the discussion first. It would be nice to hook into the implemented datastore so we can subscribe to network status changes on the client side too without having to create a new implementation of the network indicator.

**Comment by kingsleyzissou** [comment]
cc @wtrocki

**Comment by wtrocki** [comment]
+1. We had this discussions before and we kept it private but no problem to expose it.

**Comment by kingsleyzissou** [comment]
Cool, I'll add get a new PR in for that and then release. I'm just testing things in OVP at the moment to see if I can set things
up for the demo.
