### ISSUE TITLE
Conflict rebase functionality

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#119]
## Rebase Feature for Conflicts

Currently any subsequent change on the same object while offline can cause conflict. This due to the fact that any next subsequent change will be based on an optimistic response.

This causes network inefficiency - an additional roundtrip is needed to server. The server needs to fetch server state 

### Rebasing offline queue for each conflicted change

When conflict happens we know that any subsequent change in the same type will cause another conflict. This means that we can effectively query the operations for the same type and try to apply the latest server-side data on top of that using conflict strategy. Using conflict strategy before hitting the server will allow us to avoid going to a server in cases where we know that conflict will always occur. 

We had similar functionality before that was using `ConflictProcessor` abstraction to iterate through the queue. 

### Diff based offline storage

Storing diff for the offline mutation instead of the entire object will allow us to avoid the problem however it can be a controversial change.
This is due to the fact that offline change will be saved as diff. 

If the client wins approach will be taken then we may even skip saving the base leading to better storage efficiency.

**Comment by kingsleyzissou** [comment]
Closing this since conflicts will be dealt with on server-side. This implementation is also only specific to the DataSync stack, so this opinionated approach is best implemented in DataSync or Graphback.
