### ISSUE TITLE
Make offline scheduler that is not bound to apollo client/link

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#129]
Offline mutation scheduler is now part of the Apollo-link. 
This has some disadvantages as processing on link requires client.mutate to be scheduled. Ideally, our scheduler should act before client.mutate is triggered and persist the related data

See #125

**Comment by darahayes** [comment]
Happy to finally report that the initial version of `offix-scheduler` was released in [0.10.0](https://github.com/aerogear/offix/releases/tag/0.10.0) and that `offix-client` is now using that under the hood 🎉
