### ISSUE TITLE
Page fails to load online after offline refresh: item.operation.getContext is not a function

### ISSUE THREAD

**Issue by milenazuccarelli** [aerogear/offix#145]
## Bug Report

Hey guys, I am experiencing the following error: 
`Uncaught (in promise) TypeError: item.operation.getContext is not a function`

After doing the following:
1. Load my app
2. Go offline
3. Make some changes offline
4. Refresh
5. Go back online
6. Page fails to load

<img width="735" alt="Screen Shot 2019-08-07 at 12 28 31" src="https://user-images.githubusercontent.com/24867345/62620191-8a27f300-b910-11e9-83a0-0ca76e7c42eb.png">

* **Affected Package(s)**:
    offix-client
* **Package version(s)**:
    offix-client: 0.7.1

**Comment by MStokluska** [comment]
Hi @milenazuccarelli , which changes are you causing this error? Is this addMessage mutations from the app?
Also, is refreshing the page trying to refresh the link with server, which in this case would not be accessible as you are offline? I might be getting this wrong but isn't offix supporting offline as it stores mutations for later execution ( once u go back online ) while refreshing website requests response from server?

**Comment by wtrocki** [comment]
This is a critical bug introduced recently. 
Going to take look
