### ISSUE TITLE
Provide a way to clear the cache

### ISSUE THREAD

**Issue by StephenCoady** [aerogear/offix#159]
## Bug Report

We currently do not expose any way to effectively clear the application cache.

We should investigate which option is best. We could use persistor.purge().
* **Affected Package(s)**: offix-client
* **Package version(s)**: 0.8.1

**Comment by JannesV** [comment]
I really need this, when a user logs out the cache should be cleared but now there is no way for me to do so.

**Comment by wtrocki** [comment]
@JannesV Thank for letting us know. I will action this instantly and we going to include this in next release.

**Comment by wtrocki** [comment]
For the moment as a workaround you can remove index-db instances directly from the application

**Comment by JannesV** [comment]
@wtrocki Thanks for the quick response. I currently use the workaround mentioned above. Looking forward to your solution!

**Comment by wtrocki** [comment]
I will provide notification when this change will be released
