### ISSUE TITLE
Consider `dexie` over `idb-localstorage`

### ISSUE THREAD

**Issue by loganpowell** [aerogear/offix#160]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Not a problem, but could be if `idb-localstorage` becomes abandoned

**Describe the solution you'd like**
[`dexie`](https://github.com/dfahlander/Dexie.js/) is a more mature solution with a broader support structure.

**Describe alternatives you've considered**
I realize that you may be familiar with the localstorage API and this request would mean real work, so feel free to say 'sod off' :D

**Comment by loganpowell** [comment]
Nevermind. I just realized you are also the author of `idb-localstorage` :D my apologies

**Comment by wtrocki** [comment]
@loganpowell Actually this is something we need to do ourselves together with better cache persistence improvements. Back to roadmap

**Comment by kingsleyzissou** [comment]
@wtrocki if we're considering a local db for offline storage, would we still need to look at migrating idb-localstorage? For the meantime we've removed the dependency for this package and brought it into Offix.

**Comment by wtrocki** [comment]
Trick is to be able to fix problems in storage wrapper as we go (and as browsers and mobile platforms evolve) while giving developers ability to override.

Both are possible now so we can close it as there is not much we can do

**Comment by darahayes** [comment]
+1 I think we can close this
