### ISSUE TITLE
Application Crashes When no IndexedDB available

### ISSUE THREAD

**Issue by darahayes** [aerogear/offix#171]
## Bug Report

* **Affected Package(s)**: offix-client
* **Package version(s)**: all versions
* **Platform (e.g. Android/iOS)**: any platform where IndexedDB is unavailable

It is not possible to create a new `OfflineClient` when IndexedDb is not available. How you can quickly check this: Try to create a new offix client in the Firefox equivalent of incognito mode. In that mode, firefox does not allow IndexedDB usage.

I believe the error is thrown when we [create a `new Store`](https://github.com/aerogear/offix/blob/1ae680e4ad3586ee0d460315aa611a942433bf26/packages/offix-client/src/cache.ts#L6-L8).

My opinion is that offix-client should be usable even if the environment/platform has no storage capabilities at all. The main impact there would be that changes are not persisted after application restarts. I'd still rather my application working with some limitations over simply not working at all.

**Comment by wtrocki** [comment]
Initial idea was that you can pass any storage solution into the client for platform theywant to support. For example on Android this can be sqlite etc.
However, this use case is different. Under some circumstances browser itself can reject IndexedDB driver - which is used by default and.. there is no graceful fallback to anything else. 

Developers will not be able to detect/handle this as this can happen depending on browser security options etc. Handling could be:

- Print information that storage is not available (already there in form of quite uninformative error)
- Fallback to InMemory storage (as any other storage may be also not available)

I think we should probably stick with some storage wrapper by default. 
We have nice proposal from community to use dixe:
https://github.com/aerogear/offix/issues/160

This will have some fallbacks inside library.

**Comment by darahayes** [comment]
> Print information that storage is not available (already there in form of quite uninformative error)
> Fallback to InMemory storage (as any other storage may be also not available)

I completely agree. Tain problem right now is that there's no way to gracefully handle this. The error that occurs is an unhandled promise rejection that happens inside `idb-localstorage`. Right now there's no way to catch it and prevent the application from crashing.

I really like the suggestion to use Dixie. i think it could be a longer term solution but I think in the short term we need to patch `idb-localstorage` because there is a clear bug down there.

**Comment by kingsleyzissou** [comment]
This issue was fixed in pr #337
