### ISSUE TITLE
Use apollo-cache-persist-dev in offix-client

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#174]
## Feature Request

Package name changed to apollo-cache-persist-dev. Offix-client package needs update in package.json

**Comment by AdrianJVillalobos** [comment]
Hello, I would like to take this issue at @NovaHelm can you give me more details?

**Comment by wtrocki** [comment]
You need to change package name in offix-client and offix-offline from apollo-cache-persist to apollo-cache-persist-dev

**Comment by wtrocki** [comment]
Very simple issue. Must have for 0.12.0

**Comment by wtrocki** [comment]
We might also check if it will be possible to use: https://morrys.github.io/wora/docs/cache-persist
This package offers filtering capabilities and subscriptions

**Comment by darahayes** [comment]
I've been thinking about this. We now allow users to pass in their own CachePersistor instance (one is created by default if not passed). See the docs here: https://offix.dev/docs/client-configuration#cachepersistor

Perhaps we could bundle our own CachePersistor in offix client and then if users want to pass their own instance, they will use the one we export from `offix-client`. It could work something like this:

```js
import {
  ApolloOfflineClient,
  CachePersistor,
  createDefaultCacheStorage
} from "offix-client";

import { HttpLink } from "apollo-link-http";
import { InMemoryCache } from "apollo-cache-inmemory";


const cache = new InMemoryCache()

const cachePersistor = new CachePersistor({
  cache,
  storage: createDefaultCacheStorage()
})

const client = new ApolloOfflineClient({
  cache,
  cachePersistor,
  link: new HttpLink({ uri: "http://example.com/graphql" });
});
```

What do you think?

**Comment by shrey** [comment]
Is this issue still relevant?

**Comment by wtrocki** [comment]
Good point. We actually thinking of bringing the Apollo-Cache-Perist code inside the repository so dev release is not longer needed.
