### ISSUE TITLE
[Discussion] How to handle breaking changes to persistent storage?

### ISSUE THREAD

**Issue by darahayes** [aerogear/offix#187]
## Background

https://github.com/aerogear/offix/pull/170 was recently merged which made backwards incompatible changes to the format of the offline items being stored in the persistent offline store. 

This means that when we release a new version of Offix, existing applications that have data in their store will experience issues when they eventually update the version of Offix being used.

From a very top level, I see 2 main approaches to get around these issues and prevent application crashes.

1. The application can blow all of its local data away.
2. Some kind of process for migrations is put in place, either by us - the package maintainers, or by the end users of Offix.

I'd like to kick off some discussion to find a useful and repeatable solution that we will be can use to handle these kinds of breaking changes again in the future.

**Comment by wtrocki** [comment]
We going to provide release notes with follow up migration path, but developers will need to make a decision on their own:

- Make sure that all data is synced before the update 
- Remove no synced data on the update.
- Migrate dataset manually

**Comment by wtrocki** [comment]
Outdated. We have versioning enabled already
