### ISSUE TITLE
[Website/Docs] Implement Versioning in our Docusaurus Website

### ISSUE THREAD

**Issue by darahayes** [aerogear/offix#205]
## Feature Request

Docusaurus has the ability to create versions of the docs. Using a simple command like `npm run version` it will copy all your docs and place them into a folder using the specified version number. This means we can keep the docs for old versions around and then also maintain a master version.

Docusaurus has a guide on versioning. It seems pretty simple to do. https://docusaurus.io/docs/en/versioning

I would suggest we cut a version in the docs for the most recent release which is `0.8.2`.

**Comment by darahayes** [comment]
Ping @LakshanKarunathilake

**Comment by LakshanKarunathilake** [comment]
Interested in

**Comment by LakshanKarunathilake** [comment]
#217

**Comment by darahayes** [comment]
New website is live! https://offix.dev/
