### ISSUE TITLE
Document react native support

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#219]
## Task

Document react native support that will be included in the new page.
See https://github.com/aerogear/offix/blob/master/docs/react-native.md

The main target is to describe storage and network interface requirements.
See #23 for more context. 
Document both react native community version and expo using react native storage version as well.

**Comment by wtrocki** [comment]
CC @darahayes Required for release.

**Comment by darahayes** [comment]
Released in [0.12.0](https://github.com/aerogear/offix/releases/tag/0.12.0)
