### ISSUE TITLE
Apollo Client 3.0 verification

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#222]
Verify features of the Apollo Client 3.0

**Comment by wtrocki** [comment]
I have done an initial investigation of how this will work and current beta will not have any breaking changes. However there is still unclear how we going to migrate as Apollo merged all libraries into client what hopefully will not be released in official release (as it will not allow anything else than react to work).

We going to monitor situation and once Apollo-client/common package will be created I'm going to reattempt verification to see if we still ok to go. 

@darahayes My focus here is only on compatibility, however there will be couple other things that will invalidate some of our helpers etc.

<img width="781" alt="Screenshot 2019-10-30 at 22 41 31" src="https://user-images.githubusercontent.com/981838/68480200-26250b80-022c-11ea-9c18-16e6aa7be7f3.png">

This can be addressed as separate issues per feature.

**Comment by wtrocki** [comment]
Most of the focus could be on dataIdFromObject - that is used for conflict.
UpadateQuery and localState.

**Comment by kingsleyzissou** [comment]
Closing this since we have decided to deprecate the original Offix packages and move to a client-side datastore.
