### ISSUE TITLE
Enable URQL integration to new Scheduler API

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#235]
## Feature Request

URQL is an client that offers the same features as Apollo Client. 
The only outstanding feature is missing cache persistence (https://github.com/FormidableLabs/urql-exchange-graphcache/issues/61) 

We should provide separate offix package that will integrate with URLQ client to deliver offline and conflict capabilities out of the box.

**Comment by kingsleyzissou** [comment]
Closing this since we have decided to deprecate the original Offix packages and move to a client-side datastore.
