### ISSUE TITLE
Migrate to ESLint

### ISSUE THREAD

**Issue by b1zzu** [aerogear/offix#255]
## Feature Request

The typescript team has opted of eslint as main linter for typescript and the tslint community will very soon drop all work on tslint in order to focus all efforts on eslint, therfore if we want to remain up-to-date in the future we also should migrate to eslint.

More details and migration status info here:  https://github.com/palantir/tslint/issues/4534

**Comment by darahayes** [comment]
Thanks for this. This would be really nice to have but is probably low on our list of priorities right now. I'm more than happy to provide guidance if anyone wants contribute.

**Comment by kingsleyzissou** [comment]
Fixed in pr #328
