### ISSUE TITLE
Migrate offix-client integration tests to Jest 

### ISSUE THREAD

**Issue by b1zzu** [aerogear/offix#269]
## Enhancement

I'm opening this issue in order to track the migration of the integration tests from karma to jest.

I know part of the work is already done, but from what I've noticed is not yet completed.

As part of this migration, we could also start using [graphq-testx](https://www.npmjs.com/package/graphql-testx)

**Comment by b1zzu** [comment]
@darahayes @wtrocki I have time to look into this issue and finish the migration, but I'm not sure what's the current status

**Comment by wtrocki** [comment]
@darahayes Can you drop the plan for this. Do we still want to do it?

**Comment by b1zzu** [comment]
@wtrocki As we have discussed with @darahayes we are going to keep the tests in Karma. I think we can close this issue.
https://github.com/aerogear/offix/pull/271#issuecomment-559759574
