### ISSUE TITLE
How to set apollo-cache-persist options like maxSize, debug, debounce, trigger

### ISSUE THREAD

**Issue by kunaldodiya** [aerogear/offix#273]
How to set apollo-cache-persist options like maxSize, debug, debounce, trigger in react native app ?

**Comment by wtrocki** [comment]
Sadly there is no public api for that but it is very easy to do it. 

Persistor is public so.. you can set new Persistor with custom options:
https://github.com/aerogear/offix/blob/master/packages/offix-client/src/ApolloOfflineClient.ts#L52-L58

Swapping persistor needs to happen before calling init function as it is used there:
https://github.com/aerogear/offix/blob/master/packages/offix-client/src/ApolloOfflineClient.ts#L73-L76

**Comment by kunaldodiya** [comment]
Thanks, I will try and let you know

**Comment by wtrocki** [comment]
@darahayes IMHO we might need to document this issue

**Comment by darahayes** [comment]
@kunaldodiya we recently merged and released https://github.com/aerogear/offix/pull/306 (in version `0.13.1`) which allows you to create your own `CachePersistor` object and pass it into the `OfflineClient` constructor. This should let you set whatever options you require for cache persistence. You can check the PR description or [the client configuration docs](https://offix.dev/docs/client-configuration#cachepersistor) to learn how to do it. I'm going to close this issue now but please do reach out if you have any further questions/feedback/issues.
