### ISSUE TITLE
Network Request Failed when offline

### ISSUE THREAD

**Issue by kunaldodiya** [aerogear/offix#274]
If I am not wrong, this package add support for offline mutation but as soon as i switch off my internet and force restart app it shows this, how can i handle this error ?
![WhatsApp Image 2019-12-02 at 5 24 20 PM](https://user-images.githubusercontent.com/7272013/69957464-c23eeb80-1528-11ea-9c66-cd6d32903851.jpeg)

**Comment by kunaldodiya** [comment]
Can you please provide a sample React native app with offline mutation, persist cache using sqlite or asyncstorage that work 100% offline

**Comment by darahayes** [comment]
Hey @kunaldodiya thanks for logging an issue. I'm afraid this error doesn't really provide any information that can help me understand the problem. Do you have a repo with your code that I could try out? I might be able to find the issue if I can look at the code.

Please also see this previous issue where a couple of steps to use `offix-client` in react native were mentioned https://github.com/aerogear/offix/issues/23

**Comment by wtrocki** [comment]
Sample application: https://github.com/wtrocki/offix-react-native-sample

**Comment by kunaldodiya** [comment]
just created a demo app https://github.com/kunaldodiya/offix-demo

**Comment by wtrocki** [comment]
We have provided docs and sample app
https://offix.dev/docs/next/react-native

**Comment by wtrocki** [comment]
O have checked your example app and after applying wrappers from docs things work for me. However I needed to remove other links - maybe problem is with them?

Since docs and sample all exist now I'm going to close this issue, however if you will still see this problem feel free to reopen it. 

Thank you so much for improving offix
