### ISSUE TITLE
Does not work well with expo

### ISSUE THREAD

**Issue by kunaldodiya** [aerogear/offix#299]
Both @react-native-community/netInfo and   @react-native-community/async-storage gives error while using with react-native-web with Expo

step to produce
1) create react native app using expo init myApp
2) add offix client
3) run expo start:web

**Comment by wtrocki** [comment]
Hi

I looks we forgot to mention that for expo you need to swap packages to react native ones. See #23 for more context. We will add that info to docs

**Comment by darahayes** [comment]
Hi there, as @wtrocki mentioned we will add an extra note to our documentation about this particular issue with Expo. According to this Github issue (https://github.com/react-native-community/react-native-netinfo/issues/124) it should be possible to use the `react-native-community` packages starting with expo sdk version 33 and above. Which version of expo are you using? Thanks.

**Comment by darahayes** [comment]
Ahh my bad, I did some further research. It seems the `@react-native-community/netinfo` works in expo but the `@react-native-community/async-storage` one does not. Updating the docs accordingly. Thanks for logging this issue!

**Comment by darahayes** [comment]
Feel free to open again if necessary!

**Comment by kunaldodiya** [comment]
Hi, thanks for resolving issue, but I am still having issue with netinfo package, please not that when using device it works fine, but when using browser (react-native-web) does not work at all,

this is my offix client

```
import { AsyncStorage } from "react-native";

import { HttpLink, InMemoryCache } from "apollo-boost";
import { ApolloLink } from "apollo-link";
import { setContext } from "apollo-link-context";
import { ApolloOfflineClient } from "offix-client";
import { httpUrlProd } from "../libs/vars";
import NetInfo from "@react-native-community/netinfo";

const networkStatus = {
  onStatusChangeListener(callback) {
    const listener = connected => {
      callback.onStatusChange({ online: connected });
    };
    NetInfo.isConnected.addEventListener("connectionChange", listener);
  },
  isOffline() {
    return NetInfo.getConnectionInfo().then(connected => !connected);
  }
};

const authLink = setContext(async (req, { headers }) => {
  const token = await AsyncStorage.getItem("token");

  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : ""
    }
  };
});

const httpLink = new HttpLink({
  uri: httpUrlProd
});

const link = ApolloLink.from([authLink, httpLink]);

export default new ApolloOfflineClient({
  cache: new InMemoryCache(),
  link,
  offlineStorage: AsyncStorage,
  cacheStorage: AsyncStorage,
  networkStatus,
  retryOptions: {
    attempts: { max: Infinity }
  },
});

```

after setting up this with expo, i am simply running command expo start --web which does not work

**Comment by wtrocki** [comment]
Looks like react native web using different api. For react native web you can actually use existing browser api that is already embedded in offix. So I guess having codebase that enables them depending on target will be the best solution for your own needs. 

Offix works with web without any special configuration - for native rn we need those wrappers but only for native ones.

**Comment by kunaldodiya** [comment]
can you please provide example code for both web and native together ?

**Comment by wtrocki** [comment]
React Native -> requires extension that are documented 
Web -> requires no extensions - all should work

To switch between platform see: https://facebook.github.io/react-native/docs/platform-specific-code#__docusaurus
