### ISSUE TITLE
Ionic Capacitor support 

### ISSUE THREAD

**Issue by LakshanKarunathilake** [aerogear/offix#309]
## Feature Request

**Problem :**  Sample Integration of Ionic + React + Offix
Combining the Ionic 4 with React including the Offix

**Solution**
Combining some existing plugins and write a new plugin for Capacitor

@darahayes @wtrocki

**Comment by wtrocki** [comment]
Awesome idea.

**Comment by wtrocki** [comment]
Quick verification of the app showed me that to support capacitor we will need to map network interface to the one we are using: https://capacitor.ionicframework.com/docs/apis/network

Doint this will make offix work with capacitor
```js
const networkStatus = {
  onStatusChangeListener(callback) {
    const listener = ({ connected }) => {
      callback.onStatusChange({ online: connected })
    };
    Network.addListener('networkStatusChange', listener);
  },
  isOffline() {
    return Network.getStatus().then(connected => !connected)
  }
};

```

**Comment by wtrocki** [comment]
This can be resolved by documentation or we can simply add capacitor target to our showcase app (It will require updating ionic and typescript versions)

**Comment by kingsleyzissou** [comment]
The new [datasync starter](https://github.com/aerogear/datasync-starter) is built with Ionic and React on top of Ionic capacitor. 

You could create your own custom React hook to determine whether the app is connected or not. See the [`useNetworkStatus`](https://github.com/aerogear/offix/blob/master/packages/react-offix-hooks/src/useNetworkStatus.ts) hook in `react-offix-hooks` for reference.

Closing this issue, but feel free to re-open if you have any further questions.
