### ISSUE TITLE
Create new example app that uses Offix + Graphback

### ISSUE THREAD

**Issue by darahayes** [aerogear/offix#324]
The [ionic-showcase](https://github.com/aerogear/ionic-showcase) app historically was built to demonstrate use cases coming from several 3rd party services. As a result, the GraphQL client and server implementations are there but with a bunch of additional baggage.

The way the client is being used is also based on how the client historically worked in much earlier versions. Even though Offix has matured a lot, the current showcase has not evolved alongside the newer versions and features of the client.

As part of having Offix 1.0 I think it's important that we provide a sample application or a set of small applications that demonstrate Offix + Graphback working together. Ideally this is what I'd like

A sample app or a set of small sample apps that demonstrate various use cases of Offix.
I think we should power the server side using Graphback. This will help us start converging Offix + Graphback together.
Ideally the app (or apps) will be small enough that they are much easier to understand by end users and they are much more maintainable for us as a team.
Ideally we will capitalise on the demand for react (regardless of what framework you like to use, React seems to be the leading choice in the community)

**Comment by darahayes** [comment]
On the web side: To keep the examples very lightweight in terms of setup/build/configuration we might be able to use parcel for building and running them. This would allow us and users to focus on the actual code examples and not on the complexities of how to build and bundle a web application. https://parceljs.org/getting_started.html cc @kingsleyzissou

**Comment by wtrocki** [comment]
Assigning to @kingsleyzissou to come up with more granular work after discussion

**Comment by darahayes** [comment]
So thanks to @kingsleyzissou we now have a really lovely example app for react. It was merged in #345 we may have another app for react native in the future but for now I'm going to close this issue.
