### ISSUE TITLE
Stablise the storage implementation

### ISSUE THREAD

**Issue by darahayes** [aerogear/offix#325]
We've had lots of issues around storage.

https://github.com/aerogear/offix/issues/187
https://github.com/aerogear/offix/issues/218
https://github.com/aerogear/offix/issues/171
https://github.com/aerogear/offix/issues/160

I think we need to review the storage mechanism we have right now and make a decision about a couple of things.

* Do we stick with idb-localstorage and improve it or do we move to some other provider (example: Dexie)?
* Do we build a comprehensive mechanism for migrating the storage if the format changes?

**Comment by kingsleyzissou** [comment]
Closing this since we have decided to deprecate the original Offix packages and move to a client-side datastore.
