### ISSUE TITLE
[Low priority] Documentation for restful use cases

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#346]
## Feature Request

Following blog post:
https://tech.trello.com/adopting-graphql-and-apollo

We need to showcase how to adopt GraphQL in scenarios where API still can be rest. Initially, we were thinking that this can be done using the scheduler, but alternative would be to have different terminating link or local resolvers.

**Comment by kingsleyzissou** [comment]
An example of this can be found in the docs with offix-scheduler:

https://offix.dev/docs/offix-scheduler-introduction
