### ISSUE TITLE
[Client library] Flutter support: offix-flutter?

### ISSUE THREAD

**Issue by biels** [aerogear/offix#355]
## Feature Request
**Is your feature request related to a problem? Please describe.**
Using offix in a flutter project. Since flutter looks like is going to be the major player in multi platform mobile dev going forward (this is my opinion, and I truly desire that React Native is able to catch up) I think it makes sense to support it. Maybe an idea for a gsoc project? Or maybe if more people is interested we can form a team and implement it. Let me know what you think!

**Describe the solution you'd like**
Create a new repository under aerogear that will hold the client library for offix called offix-flutter

**Describe alternatives you've considered**
Using https://pub.dev/packages/graphql_flutter which is the equivalent of apollo for flutter.

**Comment by wtrocki** [comment]
Flutter will require an implementation to be done in Dart. 
I think Offix (especially scheduler) can be used as inspiration to have something like that in your own project - it is not that hard to write your own scheduler in dart. IF you will have anything done we can even link it from offix readme as we already have android implementation done.

Thank you for reaching out to us
