### ISSUE TITLE
investigate tools for measuring and finding ways to reduce bundle size

### ISSUE THREAD

**Issue by darahayes** [aerogear/offix#356]
## Feature Request

It would be nice if we can do the following: 

* find tooling that can help us analyse the overall bundle size for `offix-client`
* find tooling or approaches to reduce the bundle size
* measure the bundle size as part of our CI process

**Comment by darahayes** [comment]
cc @kingsleyzissou

**Comment by wtrocki** [comment]
I believe this is out of our control as we base on already existing bundle - Apollo 

https://bundlesize-store.now.sh/build?info=%7B%22files%22%3A%5B%7B%22maxSize%22%3A24678%2C%22path%22%3A%22.%2Fdist%2Fapollo-client.cjs.min.js%22%2C%22size%22%3A24554%2C%22compression%22%3A%22gzip%22%7D%5D%2C%22repo%22%3A%22apollographql%2Fapollo-client%22%2C%22branch%22%3A%22renovate%2Fmajor-documentation-theme%22%2C%22commit_message%22%3A%22%22%2C%22sha%22%3A%22963d48a0467e4cf6a9a0eab59b8df23a0f02b1e9%22%7D

**Comment by kingsleyzissou** [comment]
I started pruning the packages for unused dependencies and removed lodash from the react-offix hooks package. Busy investigating a way for measuring bundlesize now and adding it to the CI, just so we have a way of bench-marking things
