### ISSUE TITLE
Improve the general state of testing in offix

### ISSUE THREAD

**Issue by darahayes** [aerogear/offix#357]
## Motivation

For historical reasons, we had tests spread out across the various offix packages. We also have the integration tests folder in `offix-client`

I think we would benefit from moving all tests into a single location at a top level within the repository. That includes all unit tests and integration tests.

As part of that we should be able to fix issues around code coverage reporting and we could revisit our use of the karma test runner for integration tests.

The ultimate goals would be 

* to know where we stand in terms of code coverage
* to make the tests we have more maintainable
* make it easier to add new tests
* add more tests covering additional cases

**Comment by darahayes** [comment]
cc @kingsleyzissou

**Comment by wtrocki** [comment]
We have moved to jest. We have comprehensive set of integration tests. 
We are planning a major refurb of the repository which will involve adding more tests. Closing as we have no action here.
