### ISSUE TITLE
Local state management

### ISSUE THREAD

**Issue by psy667** [aerogear/offix#365]
How I can do local state mutation and queries like [this](https://www.apollographql.com/docs/angular/basics/local-state/#resolvers)?

**Comment by darahayes** [comment]
@psy667 The `OfflineClient` accepts all the same options as `ApolloClient` which means it is possible to pass local `resolvers` if desired. Is there something specific you are trying to do or having issues with?

**Comment by wtrocki** [comment]
@psy667 Local state by definition will work when offline.

**Comment by kingsleyzissou** [comment]
@psy667 closing this issue for now. But if you are still having issues, feel free to re-open.
