### ISSUE TITLE
[Discussion] Advanced filtering in Graphback

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#369]
## Feature Request

Graphback provides now just basic means for filtering and pagination. 
To support advanced cases we can:

1) Allow people to extend schema with queryNames that can be interpretted as queries
``
""" sql: select * ... """
findNoteByIdAndFetchCommentsOrderBy();

```

2) Use JSON Scalar for filtering that is compatible with datasource

3) Figure out custom filtering format (maybe there is some standard) and provide json schema for it so we can validate it on top of the graphql  

4) Start adding more advanced types and unions for filtering.
Really last resort option (something that http://opencrud.org does now)

**Comment by darahayes** [comment]
@wtrocki is this the right repo for this issue?

**Comment by wtrocki** [comment]
Yes. Can you elaborate?

**Comment by darahayes** [comment]
It appears to be a discussion about how to do filtering + pagination in Graphback. Would it make more sense for this issue to be in the Graphback repo?

**Comment by wtrocki** [comment]
Ah.. yes. I put that in wrong place! THat is good catch. I would be looking for that issue for ages :D
