### ISSUE TITLE
replaceClientGeneratedIDsInQueue() should update the offline store 

### ISSUE THREAD

**Issue by lucasmez** [aerogear/offix#374]
## Bug Report

* **Affected Package(s)**: offix-client, offix-scheduler

The replaceClientGeneratedIDsInQueue() method only updates the Queue in memory, but it never saves the updated Queue containing the replaced ids to the store. So in the following scenarios, mutation errors will occur:

1. Offline: User creates new entity (Mutation 1). client id is assigned to it.
2. Offline: User updates the new entity multiple times (Mutation 2...n) .
3. **Connectivity Restored**
4. Online: Mutation 1 is sent to the server. On server response, replaceClientGeneratedIDsInQueue() replaces the ids parameters on the queue _in memory_ for Mutations 2...n.
5. Online: Mutation 2 is sent to the server with correct id...
6. Online: Mutation 3 is sent to the server with correct id...

**SCENARIO 1**
7. **Connectivity Lost**
8. Offline: User refreshes the page.
9. Offline:  Mutations 4...n are restored from store into memory, but they contain old client id since replaceClientGeneratedIDsInQueue() did not update the store.

**OR SCENARIO 2**
7. Online: User refreshes the page.
8. Online: Mutations 4...n are restored from store into memory, but they contain old client id since replaceClientGeneratedIDsInQueue() did not update the store.

**Comment by wtrocki** [comment]
Thank you so much for logging this issue. This looks like serious issue that might affect replication of the queue. We going to resolve it in the comming days.

**Comment by darahayes** [comment]
Whoah thanks so much for catching this. Luckily we should be able to fix that one easily enough!
