### ISSUE TITLE
Capacitor support

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#397]
## Feature Request

When running with capacitor Cordova is still enabled however capacitor defines different api for network status and storage. We could provide capacitor specific implementations

**Comment by wtrocki** [comment]
See datasync-starter issues

**Comment by kingsleyzissou** [comment]
@wtrocki I think this could be closed and we could give an example implementation in the docs.

If we had to provide support for this, we would probably have to create a new package entirely.

**Comment by wtrocki** [comment]
Challenge is that package itself will need to link some other packages which for both react and the capacitor is kinda hard to do (as you can have conflicts on root etc.) We might bring that as requirement for 1.0 (have package for each supported platform

**Comment by wtrocki** [comment]
Happy to close it

**Comment by kingsleyzissou** [comment]
Yeah we can revisit for 1.0.0. Yeah managing it in a mono repo would be tricky with all the conflicts. Maybe we could do a package in a separate repo, but then there are issues with maintainability.

**Comment by wtrocki** [comment]
every community has patterns:

- For react-native people drop new package with peer dependencies and tell people to add them in top level

- For capacitor all packages are typically there so all we need is just create package with interdependencies. I know I have closed this but this is actually way easier and doable as packages could be an copy paste. 

Challenge for this is just that this packages typically will not compile (as you mentioned and will be really unfriendly for monorepo format. 

So solution for that is to have couple workspaces - that brings complexity of the  CI/CD into extremes but it is quite easy to configure

**Comment by kingsleyzissou** [comment]
See #470 for providing first-class support for Capacitor, React Native & Nativescript
