### ISSUE TITLE
Move link logic to separate package

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#4]
## Feature Request

Split conflict and offline features with client creation so developers can pick them separately and integrate with their apps.

**Comment by wtrocki** [comment]
@StephenCoady @darahayes  I think we might instead have conflict and offline as single package with thin client wrapping both helpers and links.

This way we can:
- promote links in apollo
- have very opiniated client that works out of the box
- have cache helpers as separate tooling for ecosystem
- use links to provide different flavours of offix ;)

Sounds like plan?

**Comment by StephenCoady** [comment]
It sounds good to me. A completely pluggable package with a client that ties everything together if required is the best of both.

**Comment by darahayes** [comment]
I really like this idea. I would go as far as to say we could split out all of the links into dedicated packages. (Offline, Conflicts, Auth, etc) into their own separate packages and then provide a composite link or even an entire client that uses those in an opinionated way.

**Comment by wtrocki** [comment]
Perfect! Added that to upstream roadmap
