### ISSUE TITLE
valueChanges not on query?

### ISSUE THREAD

**Issue by KyleBrost** [aerogear/offix#425]
When trying to convert from the regualr apollo client to the offix offline client a simple watchQuery does not work:

    this.client.watchQuery<ScheduleQueryResponse>({
      query: SCHEDULE_EVENT_QUERY_ALL,
      variables: {
        eventDate: eventDate_,
        resourceId: resourceId_,
      }
    }).valueChanges.subscribe( ({data,loading}) => {

        this.loading = loading;
        this.todos = data.todos;
    });

I get an error that "valueChanges" does not exist.  I'm wondering why if it's based on the same client and how do I get the same functionality of the valueChanges?

**Comment by wtrocki** [comment]
Offix client is using Apollo client. `valueChanges` comes from Apollo Angular which is a wrapper around Apollo Client. 

To quote docs:

```

The `watchQuery` method returns a `QueryRef` object which has the `valueChanges`
property that is an `Observable`.
```

I think that watch query has already observable so `valueChanges` can be ignored
