### ISSUE TITLE
Release package

### ISSUE THREAD

**Issue by mgobins** [aerogear/offix#45]
## Bug Report

* **Affected Package(s)**:
* **Package version(s)**:
* **Platform (e.g. Android/iOS)**:
* **Platform Version**:
* **Cordova Version**:
* **Node.js / npm versions**:

**Comment by wtrocki** [comment]
The package is released to npm already and working on a new release soon.

**Comment by wtrocki** [comment]
@mgobins See our latest release with tons of improvements. 
Closing (CC @StephenCoady )
