### ISSUE TITLE
Question: How to fix id conflicts cache/server

### ISSUE THREAD

**Issue by QuevedoIB** [aerogear/offix#456]
Hello, 

I managed to do a simple offline todo app that works fine except for the case that when the user creates a todo offline, an id field is required in the optimistic response so I pass null/uuidv4 to that field and it works as expected, but when the app comes back online and the cached queries/mutations are sent the todo is created in the api with a generated id that doesn't match the random one I've temporary set while offline in the cache so any mutation with that todo will fail because will be sent with the cache id and not the real one that's saved in the api.

I've been reading the documentation and It might be related to Conflict Server, so in the api do I need to implement a version field that is sent on every mutation request to check what's the newest/correct id? Or is there a simple/better way to solve that problem. 

Thanks a lot.

**Comment by wtrocki** [comment]
@QuevedoIB ID is not required. We have an implementation that assigns client id (with `client:` prefix and then once a mutation is finished we know that we need to remap it to the original id from the server. This happens only for create operations. 

If you providing id on the client offix will assume that your server do not generate ids and you want to set the ID from a client. This means if the server comes back with the wrong id it will not be remapped (and really strange stuff will start happening). We still have capability to provide custom mapping when operations are successfully moved to the server.


@darahayes anything to add from your side.

**Comment by kingsleyzissou** [comment]
I can't think of anything to add to this. Offix would manage the client ID generation and the only time it would be necessary to provide an ID is for delete and update mutations (in which case the ID will come from the database or the offline generated client id).

**Comment by darahayes** [comment]
Yeah if you intend for your server to create the ids then you shouldn't need to provide any on the client side as offix will generate one for you. Perhaps you can share some sample code of how you're using offix and we might be able to help you solve your issue!

**Comment by wtrocki** [comment]
Worth to mention
The challenge you might face here is that if your create operation creates nested objects - Like 

{
  name
  address: {
    street
  }
} 

For this cases, offix will not be able to generate id's and you should change your object creation to two separate calls that each will have root type and relationship id. Our team is currently documenting the use cases that offix will support as part of the https://graphqlcrud.org so hopefully, it will be easier to avoid such problems in the future.

**Comment by wtrocki** [comment]
CC @craicoverflow

**Comment by QuevedoIB** [comment]
The use case I was having was the one mentioned by @kingsleyzissou. Updating a created element that has an offix generated id. 

So for example you run an add creation that generates a todo, offix automatically adds an id to that todo, if you then run an update mutation to that todo it will queue with the offix generated id and then fail when app goes back online and mutation is sent to the server with the offix id.

**Comment by wtrocki** [comment]
Wow looks like our ID mapping stopped working.

@darahayes @kingsleyzissou We should be able to confirm that in the sample app in the repo. Make create and update when offline should fail on datasync starter or example app here.

**Comment by kingsleyzissou** [comment]
@wtrocki it's still working okay in both the datasync-starter and the sample app in the repo,

- Created a task while offline
- Edited the task while still offline
- Go back online, the task was created okay

**Comment by wtrocki** [comment]
@QuevedoIB would you be able to provide more info about the issue:
Offix will save data in IndexedDb database in your browser
1) what ID you see store when offline
2) Is it prefixed by `/client`?

This reminds me that we need to have much better logging first in the lib to be able to inspect issues like this

**Comment by kingsleyzissou** [comment]
I'll create an issue for the logging and have a look into it

**Comment by kingsleyzissou** [comment]
@QuevedoIB we are going to close this, since we are improving the debugging in Offix in general. If you are still having issues with this, please feel free to re-open.
