### ISSUE TITLE
Provide easy way for handling local data

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#464]
## Feature Request

Our cache helpers making many assumptions without telling developers about them. 
This means that offix works nicely if you have. 
Cache helpers work only with happy day scenarios - failing to cover advanced ones giving developers hard time 

## How to action this in two phases

- We can document how our cache helpers work for the use cases we have and how to address them. Possibly utilizing code generation features so developers will not need to deal with the updates. This can be done by extending graphql-code-generator and giving developers ability to supply information about affected queries/watchers. However this will work only with selected number of cases (for example future https://graphqlcrud.org spec

- Give developers more explicit and functional update function - giving them better API to update any cache object/remove data.
Apollo and URLQ cache can be used as database. This means that users can execute some of the operations on the cache and notify local or remote listeners about the new data. Operations like edits/updates can be automatically reflected. 
Developers should be able to duplicate data automatically (for example when using subscriptions or paginations)
https://coderwall.com/p/lkcaag/pagination-you-re-probably-doing-it-wrong

## Impact of this issue

This issue is an take to address numerous challenges that cache helpers faced and try to address this problem comprehensively. 
As developer you will be able to follow our patterns for building applications and get out of the box support (similar to relay etc.) or get much better update handler. 

## Affected issues

https://github.com/aerogear/offix/issues/456
https://github.com/aerogear/offix/issues/451
https://github.com/aerogear/offix/issues/447
https://github.com/aerogear/offix/issues/63

@darahayes @kingsleyzissou Looking for feedback for this idea

**Comment by kingsleyzissou** [comment]
@wtrocki sounds good, I think our biggest challenge and the most issues have been around the cache and this should add to stabilising the storage implementation.

**Comment by Eunovo** [comment]
I think "handling local data"  is a great starting point for DataStore implementation @wtrocki @kingsleyzissou 
We have moved from the approach of using graphql clients as database. So, we need storage implementation for browser(IndexedDB) and mobile(SQLite).

**Comment by wtrocki** [comment]
It is more approach where you are using GraphQL client inside some db aware wrapper. worth checking Aws datastore they have something similar

**Comment by Eunovo** [comment]
@wtrocki Can we close this?

**Comment by wtrocki** [comment]
lets focus on datastore only issues first. We leave offix generic for phase 2
