### ISSUE TITLE
Add ability to filter out what data is effectively offline and what data can be hot

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#466]
## Feature Request

Currently adding offix is going to cause a lots of problems for the app as whole as adding it means that all data will be cached and available for offline.
During conversations with the developers I found this the main factor that is blocking offix adoption - it is not easy to turn it on for certain datasets that needs to be offline

**Comment by kingsleyzissou** [comment]
Closing this since we have decided to deprecate the original Offix packages and move to a client-side datastore.
