### ISSUE TITLE
Include Apollo-Cache-Persist inside the repository

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#468]
## Feature Request
 
I would like to talk about value of maintaining https://github.com/apollographql/apollo-cache-persist/ vs having Apollo Cache persist inside the repository where we can directly release it along with the offix every time. We strongly depend on this library - with some strong performance implications

**Comment by kingsleyzissou** [comment]
@wtrocki I think we can close this issue, since we have chosen to go the datastore approach, I don't think it makes sense to bring in the library into Offix at this point.
