### ISSUE TITLE
Conflict resolution should be independent from apollo format

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#472]
## Feature Request
 
While offline is independent at the moment our conflict resolution is 
very dependent on Apollo. We need to investigate how to make it work with any client (and server side resolution as well)

**Comment by Eunovo** [comment]
@wtrocki I'm looking into this. Any pointers(or just a starting pointt in the repo) will help

**Comment by wtrocki** [comment]
hmm.. It could be total refactor of offix. I will keep it for maintainers for the moment

**Comment by Eunovo** [comment]
All right
