### ISSUE TITLE
Improved logging for Offix

### ISSUE THREAD

**Issue by kingsleyzissou** [aerogear/offix#476]
## Feature Request
Investigate better logging for Offix with more meaningful errors to assist debugging.

**Comment by wtrocki** [comment]
Two ideas:

### Debug logging
Debug lib can be used to log messages when:
- item is saved, removed off queue

### Debug listener 

Add queue listener that will print extra info

**Comment by shrey** [comment]
Hey, I would like to work on this issue, could you guide me a bit?

**Comment by wtrocki** [comment]
@shrey Amazing to hear that. We can add debug gradually. Currently the most important area is the scheduler storage interface. Different platforms have issues around that and without logging is hard to get the sense what is the problem. 

We can add debug before and after saving, getting and deleting item from queue

https://github.com/aerogear/offix/blob/master/packages/offix-scheduler/src/store/OfflineStore.ts

**Comment by kingsleyzissou** [comment]
@wtrocki closing this. This has landed in the Datstore side already
