### ISSUE TITLE
Build network state aware data replication using plain graphql client

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#49]
I think the best way to start with this is simply to enable the application to Query specific data on the server and Subscribe for results when:

- Application is starting 
- The application became online and it is on the foreground. 

We currently have `OfflineMutationsHandler` that gives the capability to resend offline mutations. 

## Proposal for client

The client can have new methods for registering queries/subscriptions:
```
client.registerOnlineQuery(new OnlineQuery({gql,variables}))
client.registerOnlineSubscription(new OnlineSubscription({gql,variables}))
```

`OnlineQuery/OnlineSubscription` apart from having all required fields to perform mutation will contain metadata used to decide when to call mutate.

For example:
```typescript
// Wait with request after becoming online
public initialDelay: number = 0; 
// Interval used for pooling
public interval?: 
// Even some extra metadata
public requiresWifi: boolean
```
Developers will be able to trigger Query Refresh manually (and force subscriptions to reconnect:
```
client.forceOnlineRefresh();
```

## Related work
0. Extend OfflineMutationsHandler to handle subscriptions
1. Create abstraction for OnlineQuery and OnlineSubscription
2. Create Registry of OnflineQueryes/Subscriptions.
Expose methods to register OnlineQueries and OnlineSubscriptions to registry
3. Connect NetworkState interface to interact with the registry and execute depending on medatadata in  OnlineQuery and OnlineSubscription
4. Write unit tests and integration tests for this feature.

**Open for comments, opinions and contributions**
We can create individual issues once the community will agree on the flow.

Discussion in #6 for more information

**Comment by wtrocki** [comment]
@Eunovo Let;s chat about this this week. Happy to explain this concept.

**Comment by Eunovo** [comment]
> We currently have OfflineMutationsHandler that gives the capability to resend offline mutations.

@wtrocki you want to build client that uses this, right?

**Comment by Eunovo** [comment]
Current offix client can handle offline mutations; You want to be able to handle subscriptions?

**Comment by wtrocki** [comment]
Forget to talk about it. Lets ignore that for the moment but bring it to the project

**Comment by Eunovo** [comment]
All right

**Comment by Eunovo** [comment]
@wtrocki data replication between Apollo's single key store(local) and server or we get started on DataStore and use our own store.
I'm kinda confused, which are we doing? I'm thinking DataStore but this issue is old and talks about using apollo

**Comment by Eunovo** [comment]
Also, it seems I don't have permission to assign issues to myself. Can you please assign this to me?

**Comment by wtrocki** [comment]
I will fix that

**Comment by Eunovo** [comment]
To this in DataStore, I think we need to do three things

- Observe events on store and pass operations to offix-scheduler(offix-scheduler can queue operations when offline)
- Subscribe to the server for data changes on app start
- Sync operations from the server(using delta queries) on app start

I think it's important we subscribe before we sync (we will receive all data that was updated between our last sync and the current timestamp taking care to dedup appropriately) so we don't miss any change that occurs on the server between the sync step and subscription step.

**Comment by Eunovo** [comment]
@wtrocki  My Idea for replication is above

**Comment by wtrocki** [comment]
> Observe events on store and pass operations to offix-scheduler(offix-scheduler can queue operations when offline)

I do think that this can be problematic due to data loss issues. You can have data in store that failed to replicate. We need to build some metadata (same as queue we have in the offix 1.0) and then manage errors of the API etc.

**Comment by Eunovo** [comment]
> I do think that this can be problematic due to data loss issues. You can have data in store that failed to replicate. We need to build some metadata (same as queue we have in the offix 1.0) and then manage errors of the API etc.

I'm sorry. I am slightly confused. The offix-scheduler does have a queue that I plan to use.  

If you are referring to failed replications due to server-side errors. What kind of errors are we looking at? If the operations simply fail because of a network error, we can simply retry it. If it's a business logic error, we might undo change to local store and throw an error to user.
For example, if a user creates an invalid note and the server rejects it we remove the invalid note from the local store and throw an error and let the dev handle invalid notes. Will the dev request the user to re-enter? I think that depends on the application.

So, what data loss issues are you referring to? @wtrocki

**Comment by wtrocki** [comment]
Actually we need to keep the Scheduler and build new offline queue. 
The new queue will work by keeping the previous version of the data so we can revert it and have client side conflict resolution. It is important for us to refactor it and use it in both pure offix and datastore. 

> If you are referring to failed replications due to server-side errors. What kind of errors are we looking at? 

Any error starting from missing authentication etc. There are range of errors that we need to deal with - our user need to deal with in some cases. Currently we have some listeners to support this and we thread every error as user error.

> we might undo change to local store and throw an error to user.

This is not going to work unless we going to hold promises for users until replication is finished. 
We need robust data replication engine (we have something like that but it is very convoluted and build around apollo framework. We need something different that will be able to not only schedule changes (scheduler) but keep the history and queue changes. Network state interface here can be added upfront as way to improve reliability - do not make requests if we definitely know we are offline etc.

**Comment by wtrocki** [comment]
> For example, if a user creates an invalid note and the server rejects it we remove the invalid note from the local store and throw an error and let the dev handle invalid notes. Will the dev request the user to re-enter? I think that depends on the application.

We cannot remove it - change we might be talking about might no longer exist or data could have been updated by subscription (or even conflicted) we need to stage changesets and know how to revert them.

Happy for us this is something we can work together with @kingsleyzissou and then reuse it in generic and datastore use cases.

**Comment by Eunovo** [comment]
> This is not going to work unless we going to hold promises for users until replication is finished.

What if the error is dispatched as an event? @wtrocki

**Comment by wtrocki** [comment]
So this what I was thinking. You get result if thing is saved to local database and then you can listen to actual events. Challenge with events is that you will need to:

A) Mount listeners in every active component
B) Have some form of global handling for the action that happened for component (people hate this) this would be our own take on Redux etc.

I think we can do that with mixture of both (currently we have global listener and promise connected to the error - so I will expect similar API here :D

**Comment by Eunovo** [comment]
@wtrocki  Thanks for the explanation. I think I get it now.

**Comment by Eunovo** [comment]
@wtrocki 
 I think that holding promises  until replication is finished doesn't work if app starts with unreplicated changes. 

> we need to stage changesets and know how to revert them.

If we stage changesets, will we rollback entire local database if an operation fails to replicate? Assuming a user makes a dozen operations and the frist one fails to replicate, do we undo all operations that occurred after the failed one? What if we had a way to allow the user define which operations are linked?

Whatever we do to handle replication errors we will need to alert user to these errors. How are we going to do that? Are we discarding the idea of error events.

**Comment by wtrocki** [comment]
Really good questions. I think all depends on how we will process changesets:

If we assume that we will aggregate data within single model then failure probably means going to affect only queue for this model. It will also depends on the strategy we will take - squashing edits/deletions into one single change can work here as well. I think to talk about subscriptions and error handling strategy we need first an basic replication engine for create edit and delete. That is critical for all of us being on the same page.

I can talk based on context from current offix but there we had relationships involved - here we decompose all to single elements - curious how other guy is doing it - maybe we can research basic replication and then have discussion about those?

**Comment by wtrocki** [comment]
> If we stage changesets, will we rollback entire local database if an operation fails to replicate? A

No. We will usually rollback affected working dataset. Things will complicate when we start counting relationships. I think we said that our operations like User.create() will never allow to specify extra objects like UsersComments. If that will be possible (as others doing it) we will need to revert entire chain of relationships. I see this as feature of the store that we going to build with Gianluca.

**Comment by wtrocki** [comment]
> Whatever we do to handle replication errors we will need to alert user to these errors. How are we going to do that? 

Please check current Offix Listeners (https://offix.dev/docs/offline-client#listening-for-events). We might chance then to cather new Observable/Reactive eventing but concept will stay the same. I think you have already similar counter part of that level listener in DataStore. Trick is to allow to reschedule changes. All of this will be really about how we design new offline queue around **existing** implementation of scheduler. 

Let's get familiar with how scheduler works https://offix.dev/docs/offix-scheduler-introduction
As for queue we will change it to hold differentials rather than actual data and the store will probably need to contain some extra flags like `_replicated:true` and `_deleted:true` to give basic information about state of the current object. I have played with this and for Offix 2.0 we will have one problem which is ability to apply change to cache that were not replicated to server, but for datastore this will be possible as datastore will be used as source of thruth

CC @kingsleyzissou

**Comment by Eunovo** [comment]
@wtrocki @kingsleyzissou 
I looked into how other guys do synchronization. There are a lot of things that are unclear but I think I understand how they handle mutations.

They have a mutation outbox queue that is processed by a MutationProcessor. This processor only works when the app is online. It divides errors into three types;

- Nonretryable
- Conflict error
- Others

I think Nonretryable is due to network problems and the processor simply halts operation.

Conflict errors are handled by conflict handlers. The result is saved to local store and replicated.

Other errors are handled by error handlers which I think are user defined. It seems that update operations are requeued while add operations are removed from the outbox queue.

**Comment by Eunovo** [comment]
>  I think to talk about subscriptions and error handling strategy we need first an basic replication engine for create edit and delete.

Sure @wtrocki. I'll work on a basic engine.

**Comment by kingsleyzissou** [comment]
@Eunovo I'm currently playing around using the scheduler and the store together to replicate the changes.

There are a couple of different approaches we could take here to achieve this.

**Comment by wtrocki** [comment]
Amazing job here guys! Yes - in fact we have the same classification in offix - network errors are usually delivered by GraphQL clients there is GraphQL app error and those really need custom handler

**Comment by Eunovo** [comment]
what if we didn't use a queue? What if we just selected all data that changed since last sync and pushed them to server. Here, we are not pushing operations. So all the changes can be accepted and rejected at once by the server(or in batches, if there are a lot of changes).

WDYT?
@wtrocki @kingsleyzissou

Also, what kind of server error would cause us to revert a change?

**Comment by kingsleyzissou** [comment]
@Eunovo interesting. How would you differentiate between a field level update or updating the whole object in the store. What I mean, if only the todo's title has changed, would you suggest sending the whole todo back to the server or only the id and the changed field?

At the moment I don't think there is a right or a wrong way, we have to see what works best for us and provides the clearest path forward.

We will definitely need `__replicated` and `__deleted` fields on the store in this case.

**Comment by Eunovo** [comment]
@kingsleyzissou  I was thinking we could always update whole object. Which approach would you recommend I start with? I'm starting the basic Replication engine. We have queue approach and the non-queue approach which I mentioned above. 
Cc @wtrocki @kingsleyzissou

**Comment by Eunovo** [comment]
The non-queue approach seems more simple. We could validate that this approach doesn't work first before looking at queue approach

**Comment by kingsleyzissou** [comment]
Yeah I think it can't hurt to try and good to start simple. I guess you can start with the non-queue approach so long and I will carry on with looking at changing how we use the scheduler and the queue

**Comment by Eunovo** [comment]
I have realised that using a non-queue approach will make it difficult to preserve order. Mutations need to arrive in order due to relationships that may exist among them. Imagine sending Comments to the server before the Post. The server must validate that data received conform to the business rules(e.g. Comments are made on existing Posts).

Unless there's an easy way around this, we need a queue.

**Comment by wtrocki** [comment]
> what if we didn't use a queue? What if we just selected all data that changed since last sync and pushed them to server. Here, we are not pushing operations. So all the changes can be accepted and rejected at once by the server(or in batches, if there are a lot of changes).

First - this is thinking only from datatore that will end up with datastore being hermetic solution and it will not allow us to use generic client. The replication engine should abstract this problem from datastore and could be plugged to scheduler to support generic use cases.

Second it has much bigger complexity due to requirement for custom replication protocol on server
which in most of the cases we do not control. This goes against us using GraphQL operations, error handling (batching work different than uniform operations etc.) While batching can be added to underlying client that does replication (and most of the clients can do that and we can batch by type as well (assuming that all things are merged). Batching is usually business decision not framework creators decision so we should not make that call ourselves - just give this as option. 

> I have realised that using a non-queue approach will make it difficult to preserve order. Mutations need to arrive in order due to relationships that may exist among them. Imagine sending Comments to the server before the Post. The server must validate that data received conform to the business rules(e.g. Comments are made on existing Posts).

Finally this will work only with squashing changes and auto squashing changes is very restrictive - there are some businesses that need to have full audit log of the changes thus squashing offline changes into one will mean they will look for other solution.

**Queue** is pretty standard approach to deliver history and proper timing. Queue can have features to squash changes etc

Also worth mentioning that for replication mechanism we need to have mutations without required fields for updates (which I believe we do thanks to https://graphqlcrud.org), but this will not be portable standard that works with every backend

**Comment by wtrocki** [comment]
> Yeah I think it can't hurt to try and good to start simple. I guess you can start with the non-queue approach so long and I will carry on with looking at changing how we use the scheduler and the queue

Scheduler implies queue and together with @kingsleyzissou we need to develop it for generic use cases anyway. This is out of the question and definitely not simpler.

**Comment by kingsleyzissou** [comment]
By changing how we use the queue, I mean more what information we store in the queue in order to revert the changes, i.e. diffs. But, have not reached this point in the investigation yet.
