### ISSUE TITLE
Please make export of MutationUpdaterFn available for offix-client

### ISSUE THREAD

**Issue by cjohn001** [aerogear/offix#490]
Hello together,
in order to be able to develop custom updaters, I currently need to import MutationUpdaterFn as follows:

import { MutationUpdaterFn } from 'apollo-client';

As you write in the documentation that apollo-client in an app can be replaced with offix-client, it would be great if you could export the MutationUpdaterFn from offix-client in order for us to get rid of this additional dependency. Thx.

**Comment by wtrocki** [comment]
Planning patch release early next week. Consider it done.

**Comment by wtrocki** [comment]
Another temp hack is to declare function as `any`

**Comment by cjohn001** [comment]
Thanks, great!

**Comment by wtrocki** [comment]
released
