### ISSUE TITLE
Wrapping client mutate function

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#5]
## Feature Request

Currently, when calling mutate functions users will need to pass generated optimistic response and also supply global cache updates. UX of that approach is quite restrictive and prevents developers from taking things even further.

```javascript
client.mutate({ 
     ...devOptions, 
     *optimisticResponse: createOptimisticResponse()*
     update: updateFn
})
```

## Proposal

Provide wrapper for `client.mutate` that will provide extra capabilities:

## Variant 1

Example parameters for wrapped mutate function: 
```javascript
client.mutate(...devOptions, 
  // Ability to control how offline state is reported
  offlineStrategy: 'failWhenOffline', 
  // Add ability to update Query cache automatically
  updateQuery: "getItems",
  // Adds automatic optimistic response based on payload
  generateOptimisticResponse: "getItems")
}
```

## Variant 2

```javascript
client.mutate(...devOptions,
  // Supplies argument that will be used to build 
  // Optimistic response and query Updates
  // Devs will be able to override them by 
  // supplying original parameters to function. 
  affectedQueries: ["getItems"]
  // Many other arguments possible
}
```

Function internally can

- Check if we are offline online
- For offline it will save changes locally
- Register update functions that will be triggered to see optimistic responses.
- Allow providing sensible defaults and better support for offline that is not limited to Apollo Link/Apollo client API.

### Pros

Doing this will give us many benefits:

- Awesome UX and Offline support out of the box.
- Simplify entire implementation (no holding mutations etc.)
- Ability to work with other clients depending on the community interest (not only Apollo)
- Ability to autogenerate cache updates (`update` fn) if dev did not supply them
- Ability to autogenerate optimisticReponse if it was not supplied
- Ability to supply extra parameters. For example, we can check if the client is offline and then return result instantly 

## Cons

- A custom client without the ability to reuse links inside 
Offline Link will no longer be sufficient to integrate that with other projects. 

## Alternatives

Keep existing implementation without the wrapper and provide a toolbox that will generate some parameters:

```javascript
const offlineArguments = offlineHelper({affectedQueries}
client.mutate(...devOptions, ...offlineArguments)
```

**Comment by wtrocki** [comment]
Dear Community 
We would like to know your opinion about this major improvement to Apollo Offline. 
We were holding off with making this decision for some time as it will have a major impact on developers. Any opinions feedback and questions are really welcome.

@2WheelCoder
@aarondancer
@amcdnl
@benseitz
@damianesteban
@darahayes
@evereq
@gihrig
@JayKan
@jtmthf
@kmelkon
@KrisKiddell
@michalbrabec
@mikekoopie
@ntziolis
@sebastianmacias
@shonie
@StephenCoady
@xtagon

**Comment by wtrocki** [comment]
ping @lterfloth

**Comment by ntziolis** [comment]
Totally see the usefulness of this. that said, given the fluid state of graphql ecosystem I would wait a little longer before going down the path of a custom client while still providing a way to reduce boilerplate code by:

- Exposing the `offlineHelper` method as you described for people that wanne do it manually
- as well as add an additional medhod to the client ala `client.mutateWithOffline()` that internally calls the above helper method for people that wanne reduce boilerplate

Any future refactoring necessary for users of this lib would be pretty straight forward should you decide to go down the path fop a custom client lateron.

**Comment by xtagon** [comment]
> Offline Link will no longer be sufficient to integrate that with other projects

Can you expand on the ramifications of this? Would it still be possible to integrate things like ember-apollo-client (which wraps Apollo Client) and still use links other than the offline link (such as Phoenix's subscription websocket link)?

**Comment by wtrocki** [comment]
@xtagon When wrapping mutate function we will be throwing some of the functionalities before client mutate will be called. 
This will mean that from the simple process of adding required links, we going to move to more complex integration that people will need to replicate. 

I really like @ntziolis suggestion. We can start with a helper (we have one for optimistic responses and now we can add one for updates. After that, we can create a uber helper for both and even expose a separate method in on the client.

**Comment by AndrewMorsillo** [comment]
I also think @ntziolis has a great suggestion. Exposing an optional method to reduce boilerplate sounds great.

**Comment by wtrocki** [comment]
Done. Documentation updated by @StephenCoady
