### ISSUE TITLE
Schema Support for DataStore?

### ISSUE THREAD

**Issue by Eunovo** [aerogear/offix#505]
To save entities to the IndexedDB, we need to create it's store first. There are two approaches we could take

1. We can create all stores that don't exist on application start
2. We can create the store when an entity is about to be saved to a non-existent store

Currently, I'm using the First approach. I do this by processing the schema and deleting and creating stores accordingly
The problem here is that, the schema can't be read from file and process on the client at runtime. A solution to this will be to get the schema from the server using an Introspection Query. But, currently, we do not need the whole schema, we just want to know the stores to create.
Which leads me to think that there might be a better way.

If we take approach 2, how do we know when to delete stores?

Also, as you may have noticed, the other lib has Model objects for entities. We also need this because we need to know all the properties of a model for filtering [see how I'm doing this on next branch](https://github.com/aerogear/offix/blob/next/packages/offix-datastore/tests/Predicate.test.ts). To avoid this, we could change the approach we take for filtering(I'm thinking something similar to Graphback's approach) so we don't need to know a model's properties.

@wtrocki @kingsleyzissou

**Comment by Eunovo** [comment]
@kingsleyzissou  We were discussing the possibility of importing the graphql file.
I was saying that we can't import from outside the client src directory. The model in Datasync-starter as an example is in `root/model`, the client src is `root/client/src`. Trying to import the model file would result in an error.

**Comment by kingsleyzissou** [comment]
Yeah, good point. It would be quite a limiting approach.

**Comment by Eunovo** [comment]
Following today's discussion, I'll define a schema config format. 

So, should it be a declarative JSON like
```js
{
    version: 1,
    models: [
        { ...taskModelDef }
    ]
}
``` 
Or should it be a code file like this

```js
export const Task = new Model(modelName, {
    title: string
});

export models = [Task];
```

I can easily say it's easier to import individual models(they are needed to perform CRUD operations) from the code file.

WDYT?
@wtrocki @kingsleyzissou

**Comment by kingsleyzissou** [comment]
I like the syntax of the second option. Nice and clean, but the first approach may be more flexible.

Just a quick question with regard to the models. Would they all be on the same version all the time, or is there a chance one model could be on a different version than another?

**Comment by Eunovo** [comment]
@kingsleyzissou the version I refer to is a schema version number. I use to determine when to update the client dB schema

**Comment by wtrocki** [comment]
1) Do we need to have column names?
2) Should version be done additionally per model to know what changed?

**Comment by wtrocki** [comment]
JSON will be easier to generate and we can provide schema for it.

**Comment by wtrocki** [comment]
How do you see version migration happening

**Comment by Eunovo** [comment]
> 1. Do we need to have column names for models?

I need them defined in a Model object for predicate generation.

> 2. Should version be done additionally per model to know what changed?

I don't need to update the db schema if model fields change
@wtrocki

**Comment by Eunovo** [comment]
> How do you see version migration happening?

@wtrocki  So, imagine pushing a new version of your app where new models have been added and some have been removed. You bump the version number to trigger a db upgrade on client device db

**Comment by Eunovo** [comment]
> Okay cool. Yeah. In terms of config the json is probably more flexible. Your you could use a plain JavaScript object in a js file.
> 
 The problem is that, the models are defined in a list. We will still need to write js code to filter the list when selecting a single model

**Comment by wtrocki** [comment]
i will need to think about this for a day

**Comment by wtrocki** [comment]
Real problem here is to give proper p
API for users. We have learned the lesson before.

Precreation of the models makes sense if we want to:

Have tight integration with schemas. 
Optimise performance on database on startup.

I think we should talk first how end user API will look like? How we want to consume this - hooks Vs context provider? And how generic this should be to support Vue/RN/Angular etc.

If I need to pass around some models thru components then this is going to be bad enough.

If we do API based on keys it will be hard to provide type safety.

Do we want service.User.create or useUser().create() or something like that.

As for initialization knowing the data structure upfront is essential - with typescript interface defining it.

Later we can add extra flags to some models to subscribe to create, pull for diffs after becoming online etc. All of that based on single well defined interface.

As for not knowing about fields. I would see if we can use codegen plugin later.

Also we need to talk how we going to make operation binding possible - so when I do create - what kind of GraphQL query gets send - and how this query is bound to this.

**Comment by wtrocki** [comment]
As for the replication it will be worth to spike CRUD replication handlers based on the GraphQL crud

**Comment by wtrocki** [comment]
To be clear I do not want anyone to answer all of those questions..I will try to cover top level API and design after some research on my side.

**Comment by Eunovo** [comment]
@wtrocki What I mean when I say "import model for querying" is this 
```js
import { User } from './models';
import { query } from 'offix-datastore';

const results = await query(User, (u) => u.name('eq', 'Test'));
```
I don't intend to pass models through context. For hooks, an API like this meets the generic requirement
```js
const { data, error, isloading, query } = useQuery(User);
query((c) => c.name('eq', 'Test'));
```

**Comment by wtrocki** [comment]
```js
import { User } from './models';
import { query } from 'offix-datastore';

const results = await query(User, (u) => u.name('eq', 'Test'));
```

What I do not like in this API is that it is not going to be easy to build type-safety on it unless using some conditional types


```typescript
import { User } from './models';
import { query } from 'offix-datastore';

const results = await query<User>((u: user) => u.name('eq', 'Test'));
```

but this looks ugly. I believe that the biggest challenges for this project would be:

1) Performance
If we decompose relationships now we will need to issue client side queries to the database.
In apollo cache approach items are linked to the specific queries making them available without such query

2) Binding to GraphQL queries to replicate/fetch data

We can base on graphql CRUD but this will mean that we will need to take out all graphback plugins and replicate them in offix somewhow

3) TypeSafety for ts API

People can use Graphql-code-generator but it is not clear how our API will be able to reuse or link to those types etc.

4) Tell me :)

**Comment by Eunovo** [comment]
> If we decompose relationships now we will need to issue client side queries to the database.

I don't quite understand. Do you mean that we will need to issue more queries to fetch relationships? or we will need to issue graphql queries?

**Comment by Eunovo** [comment]
> ```js
> import { User } from './models';
> import { query } from 'offix-datastore';
> 
> const results = await query(User, (u) => u.name('eq', 'Test'));
> ```
> 
> What I do not like in this API is that it is not going to be easy to build type-safety on it unless using some conditional types
> 
> ```ts
> import { User } from './models';
> import { query } from 'offix-datastore';
> 
> const results = await query<User>((u: user) => u.name('eq', 'Test'));
> ```
> 
> but this looks ugly. I believe that the biggest challenges for this project would be:
> 

The alternative would be to have something like
`User.query(): User`
This is new API reinforces my idea to define a model as an instance instead of a JSON config.

> 1. TypeSafety for ts API
> 
> People can use Graphql-code-generator but it is not clear how our API will be able to reuse or link to those types etc.
> 

What if the result from `User.query` matches the interface of the generated types? We could set a model to use a type like this
`const UserModel = new Model<User>()`
Where `User` above could be a generated type

WDYT?
@wtrocki @kingsleyzissou

**Comment by kingsleyzissou** [comment]
I much prefer the `User.query()` api. I believe Wojciech feels the same, but we will wait to hear what he says. 

In terms of the config, I'm not set on any method to achieve this, I would say go for the approach that works better to achieve this.

@wtrocki what are your thoughts?

**Comment by wtrocki** [comment]
@kingsleyzissou no need to wait for me. Your opinion matters even more here.

> The alternative would be to have something like

I think this is sensible, however how we going to deal with relationships?
Are we assuming that datastore is flat structure?

In GraphQL when we want to fetch users and their comments we can issue nested query and get all the data. How DataStore API call will look like?

would it be something like:
```
Users.find(1)
Comments.find(where:{userId: 3})
```

**Comment by Eunovo** [comment]
> I think this is sensible, however how we going to deal with relationships?
> Are we assuming that datastore is flat structure?
> 
> In GraphQL when we want to fetch users and their comments we can issue nested query and get all the data. How DataStore API call will look like?
> 
> would it be something like:
> 
> ```
> Users.find(1)
> Comments.find(where:{userId: 3})
> ```

This is what I had in mind. @kingsleyzissou any comment?

> One thing about `User` do you see us using codegen to generate this class. Would devs need to created it?

Devs can create it if they want to. See [the IUser interface created for a mongoose model here](https://medium.com/@tomanagle/strongly-typed-models-with-mongoose-and-typescript-7bc2f7197722). 
@wtrocki

**Comment by kingsleyzissou** [comment]
Yeah I like the api, nice and clean. My only concern is that we might have to provide loads of different query options and use cases, which is impossible. 

We would need a way to provide a custom query, but at the same time, since we aren't storing the queries, it's not trivial to implement graphql queries to query the datastore. We could try implement that, but we would be back in cache update hell.

As @wtrocki suggests, we may have to do more advanced queries over the network and use the datastore as the single source of truth. And use the scheduler and offline store to manage the mutations that may have failed due to going offline.

**Comment by kingsleyzissou** [comment]
Thinking a little bit more about this though. Querying relationships might still be difficult and would possibly have to be split into multiple queries.

**Comment by Eunovo** [comment]
@wtrocki I think we can close this

**Comment by wtrocki** [comment]
We need follow up for relationships queries
