### ISSUE TITLE
CLI tool for DataStore?

### ISSUE THREAD

**Issue by Eunovo** [aerogear/offix#525]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We need Model types to be created for use with DataStore. See #505 

**Describe the solution you'd like**
A tool to generate resources required for DataStore. I believe that what we do in DataStore should have nothing to do with Graphback so if we are generating DataStore resources we should do it in offix and not worry about Graphback.

**Describe alternatives you've considered**
Creating a plugin(Graphback or Graphql-codegen) to generate the resources instead of doing it in Offix. 

What I'm saying is this, "Is the resource generation a feature of DataStore?" If yes, the resources required by Offix DataStore should be generated by an Offix DataStore CLI tool. What this means that no user is forced to use Graphback or GraphQL-codegen or some other codegen tool.

Also, there is talk about `graphback-client`. I understand the "graphback client" to be a plugin to generate client query documents. This function is not related to DataStore in any way that I know of, so, why move or modify the "graphback-client"?.

@wtrocki @kingsleyzissou

**Comment by kingsleyzissou** [comment]
It makes sense to have an offix-cli to generate the necessary resources required for datastore. +1 for that.

But, I think the idea is that the offix-cli could be responsible for more than just the datastore resources. At the moment, as you say, graphback is responsible for some of the resources used on the client-side, and that is something we would like to move away from.

**Comment by Eunovo** [comment]
> But, I think the idea is that the offix-cli could be responsible for more than just the datastore resources. At the moment, as you say, graphback is responsible for some of the resources used on the client-side, and that is something we would like to move away from.

@kingsleyzissou 
This is what I understand;
- Graphback is a tool that helps developers set up a Graphql application.
- It has a client plugin to generate client documents.

I don't see how point two is bad as it does not contradict the purpose of Graphback.
So, what resources are you referring to? The problematic ones that we don't want Graphback to generate.

**Comment by wtrocki** [comment]
So long story short is that DataStore needs to use certain format of the queries based on the models. 
It is valid point that offix CLI needs to be separated from Graphback.
It is valid point that offix datastore should work without Graphback as well.

However, how we can ensure that we dealing with the GraphQL schema that datastore will expects us to deal with? We will do that thru https://graphqlcrud.org spec which has reference implementation in **Graphback**. 

That being said we will need to conform to some standard (this standard) and this standard is being offered by Graphback at the moment. For people to not being confused we might look for building some replication engine in the datastore so you can swap from GraphQLCRUD.org format to your own, but that will not be our intermediate target. 

Also while it is not part of your GSOC but our team also looks for cost of maintaining things as whole,
this means that having 2 places for maintaining client-side generation queries (with most of the code being similar) is too much. That is why we probably want to bring all client side capabilities to the offix to maintaining it in the single place and leave graphback to be only backend-specific.

**Comment by kingsleyzissou** [comment]
Wojciech pretty much said the same points as what I was going to say.

Maintainability is a big one here and so it doesn't make sense to be maintaining two different CLI's. For the sake of separation of concerns, it makes sense to have the client-side library handle the resources that it will need. And I agree that it feels like that is currently out of place in Graphback.

For the rest, we can and should be using the GraphQLCRUD specification to achieve this.

I would also be less inclined to move the datastore capabilities to Graphback, definitely makes more sense to have it on Offix.

**Comment by wtrocki** [comment]
Cli needs need to generate:

- Models
- Models predicates
- Typings

**Comment by wtrocki** [comment]
@Eunovo Did we missed anything from CLI perspective?
Do you see any other action needed apart from generate?

**Comment by Eunovo** [comment]
For now, No. I will state any I discover in the future.

**Comment by wtrocki** [comment]
@craicoverflow WDYT about moving client side query generation to offix.

What should be the package name? 
Opinions:
offix-cli
graphqcrud-cli
graphqcrud-client
graphqcrud

**Comment by craicoverflow** [comment]
I'd prefer it under offix namespace/organisation

Calling it graphqlcrud - this could be confusing for people that thinks "oh this gives me every possible implementation from graphqlspec from graphqlcrud, where in reality is this probably will not be the case, or will it?

**Comment by wtrocki** [comment]
I think that will be better

**Comment by Eunovo** [comment]
> Cli needs need to generate:
> 
> * Models
> * Models predicates

Should have been "Model Predicate Types"

> * Typings

@wtrocki There is no need to generate types for Model Predicates any more. Lastest push to #527 contains code that infers Model Predicate Types from the Model Type

**Comment by wtrocki** [comment]
Nice! I think @kingsleyzissou were looking to play with the example app. 
I will review this now and we can look into reading feature branch and add the ability to test it with the offix sample app (it will require an update of graphback)

**Comment by Eunovo** [comment]
@wtrocki

**Comment by Eunovo** [comment]
@wtrocki I'm looking at how we can reuse types from graphql-codegen for models. The types generated include relationship field type which we don't support

```
export type Comment = {
  ...,
  /** @manyToOne field: 'comments', key: 'noteId' */
  note?: Maybe<Note>; // here we would have noteId: string
};
```

**Comment by wtrocki** [comment]
Yep. Codegen will not work here as it is designed to work with generic graphql clients.  I think we can bring codegen only when we will have relationships investigation done. 
If you really want to do it now - check graphback client side generator. We can transform schema and replace relationships fields as we do there - but I do not think that is great idea.

CC @kingsleyzissou

**Comment by Eunovo** [comment]
We have built codegen plugin for graphback.
