### ISSUE TITLE
Predicate to Graphql filter for Replication of "UPDATE" and "DELETE" operations

### ISSUE THREAD

**Issue by Eunovo** [aerogear/offix#553]
"UPDATE" and "DELETE" operations are performed in DataStore by using predicate functions to filter the data that is affected. To replicate these operations, we need to generate graphql filters for each predicate.

Currently, the Replication Engine depends on interfaces and is not tied to GraphQL technology and even the GraphQL implementation is not tied to the current GraphQLCrud spec. That means that the filters generated for each predicate need to be in the GraphQLCrud layer which for now, comprises of the `GraphQLCrudQueryBuilder`.

We could avoid this problem by pushing each updated entity in the store instead of trying to replicate the user operation.

WDYT? To replicate the operation or to push updates as single mutations without filters.

cc @wtrocki @kingsleyzissou

**Comment by Eunovo** [comment]
@wtrocki  I'm looking at [GraphqlCrud specification for update](https://graphqlcrud.org/docs/next/update) and it doesn't allow the use of advanced filtering as we have in [specification for find](https://graphqlcrud.org/docs/next/find#filtering).

Datastore supports advanced filtering for update and delete operations. I wanted to build a converter to convert DataStore filters to Crud spec filters(the kind used in find operations) to allow an Update operation affecting multiple rows to be pushed once but it seems like this won't be possible and we have to push such a large update operation as many update operations affecting only one row.

**Comment by wtrocki** [comment]
We do not have support for batch updates. Only single updates this means that we do not need any of those yet. We might bring that but that will mean that we need to build it for graphback first.

**Comment by Eunovo** [comment]
Since we won't be replicating updates in batches(at least not for the time being), I'm going to close this.
