### ISSUE TITLE
Question: Multiple idField in optimistic response

### ISSUE THREAD

**Issue by ganashreeravikumar** [aerogear/offix#555]
I have a use case where mutation 1  creates multiple contact and response is as shown below:

**Multi-contact response:**

```
response {
  data: [
       [ '1', 'name', '12121' ]
       [ '2', 'name1', '343434' ]
       [ '3', 'name2', '565656' ]
   ]
}
```

And mutation 2 uses the contact id from mutation 1 like below:

**Entry response by contact id:**

```
input: { 
  id: '1'
  contactId: '2', // corresponding contact  [ '2', 'name1', '343434' ]
  value: 'abc'
}

```

Is there a way to add idField for all the contacts in the optimistic response of mutation 1? So that the id gets replaced in mutation 2 once mutation 1 successful. 

**Multi contact response:**

```
response {
  data: [
       [ 'client:1234', 'name', '12121' ]
       [ 'client:1235'', 'name1', '343434' ]
       [ 'client:1236', 'name2', '565656' ]
   ]
}
```

**Comment by wtrocki** [comment]
I think for that would will need to supply your own update functions and optimistic responses.

**Comment by kingsleyzissou** [comment]
Hi @ganashreeravikumar, this would be a limitation for how the optimistic responses and update functions work with Offix at the moment. We are working on ways to improve this, but this particular use-case, it would be better for you to supply your own update functions and optimistic responses as @wtrocki suggests.

**Comment by kingsleyzissou** [comment]
Hi @ganashreeravikumar, we have made the decision to move away from the Apollo client and we have decided to deprecate our Offix packages and release our Datastore. I will be closing this issue, but if you have any questions, please feel free to let us know.

You can see the docs for the updated datastore here:
https://offix.dev/docs/getting-started
