### ISSUE TITLE
Evaluate how current engine will work with SQL lite

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#572]
## Feature Request

// Evaluate how SQL Lite can be supported.
// Capacitor or ReactNative or WebSQLLit

**Comment by Eunovo** [comment]
The parts of the engine that are affected by SQLite are;
- Predicates (see solution below)
- Storage (here we just need to create another StorageAdapter for SQLite)

Currently, the same class that defines the predicates also executes them, now, we are going to require different predicate executors(each specific to Storage implementation)

Also, we will need to split up the current datastore package into;
- DataStore Core - contains code used by other packages like Predicates, StorageAdapter interface etc.
- DataStore - will contain DataStore, Models, Replication
- IndexedDB DataStore Storage Implementation along with PredicateExecutor
- React Native DataStore Storage Implementation along with Predicate Executor
- Capacitor DataStore Storage Implementation along with Predicate Executor

WDYT?
CC @wtrocki  @kingsleyzissou

**Comment by wtrocki** [comment]
All good. However doing that now will bring necessary slowdown to what we do IMHO.
What I like in this spike is that we know that our approach will not be invalidated by SQL lite. 
Means that we can still have the same predicates on that database and it will be just matter of building such abstractions. Adding this abstractions to early will brings more work when we will correct API. Amazing work. 

We can either keep this open or close if you want ot create follow up based on this investigations

**Comment by wtrocki** [comment]
Done by @kingsleyzissou

**Comment by wtrocki** [comment]
Actually we might need to test this with AsyncStorage provider etc to see how to match API. etc.

@kingsleyzissou maybe we can create follow up issue
