### ISSUE TITLE
Filter Operators for DataStore

### ISSUE THREAD

**Issue by Eunovo** [aerogear/offix#580]
## Feature Request

The Operators currently available in DataStore doesn't contain all or enough of GraphQLCrud operators. 

These operators are also not typesafe.
For example; you can do this `p.anyField("gt", 5)` or `p.anyField("gt", "random string")`  in current DataStore without any compile time error.

Two things are wrong here;
- The "gt" operator should only be available on number fields
- The "gt" operator should only accept numbers as inputs

cc @wtrocki  @kingsleyzissou 

Edit:
See:
https://github.com/aerogear/graphback/blob/master/packages/graphback-core/src/runtime/QueryFilter.ts

https://github.com/aerogear/OpenVolunteerPlatform/blob/master/platform/client/src/dataFacade.tsx

**Comment by wtrocki** [comment]
We can close this https://github.com/aerogear/offix/issues/571 issue as duplicate.
