### ISSUE TITLE
DataStore example should support more than just single model and filtering

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#581]
## Feature Request

In early versions of the offix we made mistake that we have been using 
example app that was too simple. Before we do official release we need to test how example app will work with multiple models - comments.

While I see that we have separate per model store, but actual hooks implementation we have will simply not work to fetch data if they rely on results from previous query (hooks need to be lazy etc.)

**Comment by kingsleyzissou** [comment]
@Eunovo

**Comment by wtrocki** [comment]
Creating another model to fully test replication use cases.
