### ISSUE TITLE
Datastore Replication - Incorrect Mutation Inputs

### ISSUE THREAD

**Issue by kingsleyzissou** [aerogear/offix#588]
## Bug Report

Datastore replication issue:

`"Unknown type "CreateTodoInput". Did you mean "TodoInput"?"`

and

`"Unknown type "MutateTodoInput". Did you mean "TodoInput"?"`

Using `graphql-serve`

**Comment by kingsleyzissou** [comment]
@wtrocki @Eunovo

**Comment by wtrocki** [comment]
We need to use grahql-serve 0.14.0-beta3. That is the version that has support for graphql-crud. 
I do not see this errors when using this versions

**Comment by kingsleyzissou** [comment]
@wtrocki i was using npx though, not sure if hat was pulling the latest version then

**Comment by wtrocki** [comment]
We haven't released any of this yet so we need to use qualifier even when using npx
