### ISSUE TITLE
Current network listeners and hooks rely on client

### ISSUE THREAD

**Issue by kingsleyzissou** [aerogear/offix#590]
## Feature Request

The current hooks rely on the client. I think going forward, the network listeners, if we use them, shouldn't be dependent on the client. We should be able to provide the network listeners as a separate package possibly and the react hooks could require that package directly.

This should be fairly trivial, but I could see it bringing some value to what we are doing.

This is evident in the datastore app where we would have to bring in our own network listener logic to show if the client is online/offline.

**Comment by kingsleyzissou** [comment]
@wtrocki @Eunovo WDYT?

**Comment by wtrocki** [comment]
Closing as we will need to have generic package capabilities that will enable network status.
