### ISSUE TITLE
Replication engine user API

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#591]
## Feature Request

With replication engine write operations will be replicating local writes based on events, 
but we need users to be able to interact with the replication engine to fetch data.

I believe that we need this abstracted in 2 places:

- Global config - for subscriptions and initial seed queries + rules about deltas
- The method in the model - that will return replication engine for this specific model

## Global config

We can pass specific replications flags as 3th argument when creating model.
Without flags no replication should be enabled
<img width="743" alt="Screenshot 2020-07-10 at 09 51 12" src="https://user-images.githubusercontent.com/981838/87136141-f5054b00-c292-11ea-9e8d-6ed90ede6aad.png">

## Model method

Here we can expose replication engine for specific model: 
```ts
TodoModel.getRemote().reset(resetPredicate)
TodoModel.getRemote().forceDeltaQuery();
```
Question - do we remember predicates globally for the model or allow users to specify them.
We need to map predicates to GraphQL filters etc. Maybe we could simply allow developers to specify GraphQL queries etc.

**Comment by Eunovo** [comment]
> We need to map predicates to GraphQL filters etc. Maybe we could simply allow developers to specify GraphQL queries etc.

To enable predicate to filter mapping, we have to;
- Expose predicate details like operators and values 
- Build Mappers that would recursively transform predicates using its details to filters

For example
Imagine this predicate `p.id('eq', "test")`
All we need to map this is;
- the property name
- the operator
- the input

For expressions, we have to parse the predicate expression tree recursively.

We have to implement these mappers because we will also need them if when we want to fetch more data from server(because the Datastore won't have all the data) matching a user's query

**Comment by Eunovo** [comment]
Replication Engine was meant to handle synchronization. To just pull data from server, the Model doesn't have to use the engine. It can use any API client. We will definitely need to pull data in seeding and in fetching more data matching query and these operations are not sync operations.

We can pass replication config internally to the ReplicationEngine. What I mean is that, the user creates a model with various replication config but those config are not passed to the Model instance. They are passed to the ReplicationEngine for that store. The Engine would essentially have a map of storename to config the way we have a map of storename to queries.

**Comment by wtrocki** [comment]
> We have to implement these mappers because we will also need them if when we want to fetch more data from server(because the Datastore won't have all the data) matching a user's query

But that is what this issue is about. We want to use this to create initial projection of the data. 
We missed point here: 
1) Should we use graphql queries for fetching this data or use the same predicate like stuff we have for local data? GraphQL query (or just input arguments to query) could be more natural but also hard to type and enforce

2) Would you be looking for different abstraction for Queries and Subscriptions and replication engine to be dedicated to mutations only? 

This is critical and I'm not sure if we have understanding of this.

**Comment by wtrocki** [comment]
> Replication Engine was meant to handle synchronization. To just pull data from server, the Model doesn't have to use the engine. It can use any API client. We will definitely need to pull data in seeding and in fetching more data matching query and these operations are not sync operations. 

Not sure what you mean. Can you actually put some examples of API for querying and subscription purposes. Maybe can you work on this prototype to see if we can have it

**Comment by wtrocki** [comment]
We need to check how firebase and AWS does this
