### ISSUE TITLE
Model name should be different to type

### ISSUE THREAD

**Issue by kingsleyzissou** [aerogear/offix#619]
## Feature Request

This means that you can have multiple objects in dB that are represented.by single type in backend
Each of those will have different deltaSync, pagination etc

Example - Tasks - assigned - no pagination

Completed smaller number of info paginated to 100 ordered by date
This way we do not need to bother much by predicate filters as people could operate on small.datasets
And filter on server more

**Comment by wtrocki** [comment]
Done by @kingsleyzissou - Schema has nice separation for this.
