### ISSUE TITLE
offix-client version 0.6.0 not part of latest release

### ISSUE THREAD

**Issue by areel** [aerogear/offix#62]
## Bug Report

* **Affected Package(s)**:
* **Package version(s)**:
* **Platform (e.g. Android/iOS)**:
* **Platform Version**:
* **Cordova Version**:
* **Node.js / npm versions**:

/packages/offix-cache/package.json has offix-client@0.6.0 as a dev-dependency but this version has not been publicly released.
Perhaps offix-client@0.6.0 omitted by mistake from last release cycle?

**Comment by wtrocki** [comment]
Ah.. we did not catch that issue as this package is required in dev dependencies only and we use Lerna for development that mounts package. Thank you for the logging issue. I have fixed that by the manual release which is not ideal as we have automation in place. Going to release 0.7.0 soon to cover all these problems. 

FYI @StephenCoady
