### ISSUE TITLE
updating multiple instances of a query that contain dynamic parameter values

### ISSUE THREAD

**Issue by areel** [aerogear/offix#63]
## Feature Question

Hi

I came across your libraries while looking for an offline Apollo solution BUT your offix-cache is also of interest because I have would like a simple/clean method to update the cache when you have multiple occurrences of the same query in your cache that differ on their parameter values.

an example:
- You have a parent entity with a list containing children.
-  The parent with its children is referenced by many queries.
-  We delete one of the children.
-  We now need to update all queries that reference that parent in order for its list of children to be updated.

Reading your documentation, I get the impression that in order to identify queries in the cache, you need to provide the values that those queries used. Am I correct?

Our use cases would include dynamic user values being used within queries, so it may not be possible to provide parameter values.

Any clarification appreciated.

**Comment by wtrocki** [comment]
Hello

To fully understand your case we will need to see example of cache and operations that we will expect to perform. What will be expected state of the cache before and after cache changes?

For example:
Before:

![Screenshot 2019-06-18 at 15 10 44](https://user-images.githubusercontent.com/981838/59692101-2882bc80-91dc-11e9-8f1f-df8f4cef880e.png)

After:
![Screenshot 2019-06-18 at 15 08 06](https://user-images.githubusercontent.com/981838/59692102-291b5300-91dc-11e9-820d-2b6890fa610a.png)

**Comment by wtrocki** [comment]
We are aware of the cases where helpers may not work (like pagination), but your case looks very complex, so having any info back can help us to understand it and provide the most generic option (if there is one :) )

**Comment by areel** [comment]
Was just about finishing this reply when your last comment came in.

The example shown below was chosen as it was easiest for me to create.

One of our scenarios is supporting basic CRUD operations. It is assumed the user would be able to traverse over sets of data and perform ad hoc CUD. An example UI could be a grid that supports pagination and differing page sizes. 
The following screen shots show:

- We have a parent with a list of children, 
- initially 1 child is shown, 
- we increase the pageSize to 2, 
- then increase the pageSize to 3. 

We will now have 3 queries, each time we increased the pageSize a new query was issued. 

![Screen1](https://user-images.githubusercontent.com/573567/59710633-3991f480-9201-11e9-8ab5-fc1626c47407.png)
![screen2](https://user-images.githubusercontent.com/573567/59710650-46164d00-9201-11e9-9d50-c6e4049d678a.png)
![screen3](https://user-images.githubusercontent.com/573567/59710659-4a426a80-9201-11e9-8ab9-a50b649da8ec.png)

The cache looks like
![screen4](https://user-images.githubusercontent.com/573567/59710677-4f071e80-9201-11e9-9888-65ddae49e6fa.png)

We can see child1 is referenced in 3 of them, child2 is referenced in 2 of them and child3 is referenced in 1. 

If we decide to delete child1 we would need to identify all these queries and remove child1 from each connection. 

This example also reveals other issues to overcome, if we can identify all the queries correctly and remove child1 correctly, all the queries are still incorrect e.g. our first query will now return no children when it really should now return child2 and its cursor info is incorrect too. But that is another topic and currently I think in this particular scenario we would have to accept new network queries being committed. 

Getting back to this question another scenario could be having a complex UI whose components are showing overlapping aspects of an entity and one component permits deletion. We would again need to identify a set of queries with differing parameters.

Hope that clarifies.

**Comment by wtrocki** [comment]
I have done a quick investigation and evicting root level elements is still not supported inside the apollo-cache: 
https://github.com/apollographql/apollo-client/pull/4917

We can manipulate only queries at the moment.

However, I recognize the problem of not knowing the variable (for pagination use cases). This is something we can definitely fix in future release

**Comment by wtrocki** [comment]
More investigation lead me to conclusion that we need to support paggination as separate case in the update helpers. This was also pointed in #69. 
We are going to put separate issue how to address that problem soon.

**Comment by kingsleyzissou** [comment]
Thank you for your feedback on this. We are working on implementing a pagination container to handle dynamic parameters and we are looking at refactoring how we handle cache updates and optimistic responses.

We will open a separate issue for the refactor and link it here.
