### ISSUE TITLE
Unsubscribe method for network listeners

### ISSUE THREAD

**Issue by kingsleyzissou** [aerogear/offix#637]
## Feature Request

Currently the network listeners work, but there is no way to unsubscribe from the observable. This could potentially cause a memory leak as a new subscription is registered on when the app comes back online. This has been currently marked as a TODO for now, as the implementation of this is not straight forward.

**Comment by wtrocki** [comment]
This was done with the notion that networkStatus will be available externally. 
I think that will be job of the offix generic (we even have package for this)
DataStore has network indicator that is much more complex and takes into consideration multiple factors:

- If request to server failed with `network unrechable`
- If Subscription was disconnected
- Last and not least if device has no wifi and mobile reception 

Indicator will never need to unsubscribe (and it's own subscription is composable of all events seen above.

**Comment by wtrocki** [comment]
Closing @kingsleyzissou but feel free to reopen
