### ISSUE TITLE
Use JSON Schema for model definition 

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#646]
## Feature Request
 
When defining models developers can declare both data requirements but also validation.

```ts
export const user = {
    version: 0,
    type: 'object',
    properties: {
        id: {
            type: 'string',
            primary: true
        },
        name: {
            type: 'string'
        },
        color: {
            type: 'string'
        },
        updatedAt: {
            type: 'number'
        }
    },
    indexes: ['name', 'color', 'updatedAt'],
    required: ['color']
};
```

Since we will need to generate those from GraphQL schema we will have limited information available
(only type, required and relations)

The generated source should be editable as users might add more info into those files.

## Approach 1

We generate API from GraphQL schema to JSONSchema

Pros:
- Easy to do (multiple libraries available)
Cons:
- Lack of typing supports

## Approach 2

Generate typescript objects from GraphQL Schema and then transform them 
Example:
https://github.com/YousefED/typescript-json-schema/blob/master/test/programs/comments/

**Comment by wtrocki** [comment]
Challenge here is to how we mix edits and generation to avoid overwrites.

**Comment by Eunovo** [comment]
If the json file is going to be generated, then users can't edit it. We'll have to move user editable fields somewhere else or we can allow users annotate the original Graphql schema so they won't have to edit stuff like indexes.

**Comment by Eunovo** [comment]
Why not mark individual properties as indexes instead of defining an indexes array?

**Comment by wtrocki** [comment]
How about we use generated files and decorate them when creating model in the code.

So model definition will be two files:

userModel.json
userModel.ts

In ts file we will import the JSON file and allow developers to modify it - interact with our API etc.

**Comment by kingsleyzissou** [comment]
@wtrocki Do you see the json schema handling some of the per model config? i.e. enabling delta sync for the specific model?

**Comment by wtrocki** [comment]
No.. See #648 Replication itself will be enabled on build model object (and this will be just override for global config supplied and tons of defaults

**Comment by Eunovo** [comment]
> * Relationship (Array etc.)

Once again, why an array? Why not mark properties like this

```
...
       name: {
            type: 'string',
            index: true, // if 'name' is an index
        },
        postId: {
            type: 'string',
            relationship: 'many-to-one' // many comments to one post
        },
...
```

**Comment by wtrocki** [comment]
Let's ignore relationships in this initially. 
We would want scalar and relationships support at some point (the separate issue is created already)

**Comment by kingsleyzissou** [comment]
@wtrocki @Eunovo I think the benefits of using an array to hold some of this information is that we don't have to iterate through each field in the schema to gather the information. It's only a slight benefit. Although it might be easier to generate the schema and add these as properties to each of the fields.
