### ISSUE TITLE
Ability to integrate with graphql-dotnet server ?

### ISSUE THREAD

**Issue by Hasan-git** [aerogear/offix#65]

**Comment by wtrocki** [comment]
We are backend agnostic so as long we are using js on client side most of the functionalities will work. The conflict part has server side implementation that is optional - to detect conflict but we can explain approaches here so you could replicate this in dotnet server with no issues.

**Comment by jalchr** [comment]
We are looking forward to see how could this be done in dotnet. 
Could you provide a sample code or a blog post or provide some guidelines ?

**Comment by wtrocki** [comment]
Yes. Server side will be really simple and we have PR opened that will describe that currently.

TL;DR it will require you to return specific graphql error on conflict containing server and client data. I would be cool to add that package here as well as contribution once we done it and test it

however conflict part is not required to start using offline client. Without server conflicts will not be detected but everything else will work nicely

**Comment by wtrocki** [comment]
Mentioned PR: https://github.com/aerogear/offix/pull/54

**Comment by Hasan-git** [comment]
In-progress

**Comment by wtrocki** [comment]
My recomendation will be to create separate folder with the readme and call it something like dotnet server.

**Comment by wtrocki** [comment]
The documentation contains the specification of how conflict can be implemented: https://offix.dev/#/ref-conflict-server?id=conflict-resolution-specification-for-other-languages

Implementation is very simple - we just need error on conflict and developers should be able to implement this easily outside node.js

FYI @bofarrell Conflict server will work with other middleware languages like java.
