### ISSUE TITLE
DataSync Documentation

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#659]
Documentation proposal. Still not sure how we can join datastore with existing offix docs (which are incredibly outdated)

## Introduction

- [x] Introduction to Offix DataSync
- [x] Geting started
- [x] Offix DataSync principles
- [x] DataSync models
- [ ] DataSync documents

## Local operations

- [x] CRUD operations
- [x] Filters
- [ ] Bulk operations
- [x] Subscribing to local changes

## Replication

- [ ] Replication
- [ ] Sending changes to server
- [ ] Delta queries
- [ ] Live updates
- [ ] Binary data

## Platforms

- [x] React
- [ ] React Native
- [ ] Angular
- [ ] Vue

## Server

- [ ] Introduction to Graphback
- [ ] Graphback DataSync server and Offix DataSync client

## CLI

- [x] Usage
- [x] Generating models

## Advanced concepts

- [ ] Working with generic GraphQL queries
- [ ] Swapping replication engine
- [ ] Replacing storage 

Inspiration. Check:
https://docs.mongodb.com/manual/core/document
https://pouchdb.com/guides/documents.html
https://firebase.google.com/docs/firestore/data-model

**Comment by wtrocki** [comment]
I have been working on the architecture and I always tend to design general docs when doing so. 
Looking for opinions on the chapters. We can kickstart documentation once we will land core - earlier then better. I have main problem which is how we split datastore (2 different docs on the website - similar to Apollo docs ?

**Comment by kingsleyzissou** [comment]
Yeah as per my comment in the PR, things have been changing so quickly, that it's probably better to have a dedicated docs sprint.

I like the structure that you've suggested here, it seems like it takes you through all the principles nicely.

**Comment by Eunovo** [comment]
> I have main problem which is how we split datastore (2 different docs on the website - similar to Apollo docs ?

Have a documentation home-like [Apollo](https://www.apollographql.com/docs/) would be great.

**Comment by wtrocki** [comment]
Closing as we have a solid base for docs. Any improvements will be done separately in individual issues.
