### ISSUE TITLE
Remove excessive generics inside model/predicates/queues etc.

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#672]
## Feature Request

Since we will be able to generate types we do not need so much generics in so many places and we can replace them with actual interface instances.

In most of the cases our T generics ending as unknown anyway.

**Comment by wtrocki** [comment]
I think we have done that by moving to `Filter` but assigned to Eunovo to confim

**Comment by Eunovo** [comment]
Yes, @wtrocki  Moving to `Filter` remove all the predicate generic stuff but Filter itself is generic for type validation. So, I don't know if you'd consider that excessive if you don't we can close this issue.

**Comment by wtrocki** [comment]
All good. Closing. We can address individual cases. Tested this and typings work nicely.
