### ISSUE TITLE
When using pagination in my queries with @connection directive I only get the first 1000 items from watchQuery

### ISSUE THREAD

**Issue by cjohn001** [aerogear/offix#678]
Hello together,
as mentioned in the title, I have a problem when querying larger amounts of data (>1000) using pagination. If I query more then 1000 items, it seems like the items are stored in the cache, but watchQuery only returns the first 1000 items from the cache. Is there some kind of config option how I could increase this limit?

**Comment by wtrocki** [comment]
Offix abstracts from pagination itself. Is your pagination not working (thus 1000 entries) or this is limit? I also checked the apollo cache with some helper and was able to get more than 1000 items. We use Apollo for all of those.

**Comment by cjohn001** [comment]
Hello @wtrocki ,
sorry for the effort. It was indeed a bug in my pagination. I think my configuration of the cache storage was too small. I will close the issue.
