### ISSUE TITLE
Cache redirects are not exposed to clients

### ISSUE THREAD

**Issue by Hasan-git** [aerogear/offix#69]
Documentation it's a little bit confusing, can you provide us with samples ?

------------------------
EDITED BY @wtrocki

Target of this issue is to document way developers can specify Apollo Cache Redirects. 
Those redirects needs to be specified when creating InMemoryCache 
https://github.com/aerogear/offix/blob/master/packages/offix-client/src/OfflineClient.ts#L102

Currently there is no way to do so

**Comment by wtrocki** [comment]
What particular parts of the documentation are problematic?
We are actually working on improving documentation and sample app so any feedback is more than welcomed.
Offix is used in https://github.com/aerogear/ionic-showcase. 

Demo video: https://www.youtube.com/embed/CrYinCtTHds

**Comment by Hasan-git** [comment]
**All human beings will be thankful for your efforts** 

> What particular parts of the documentation are problematic?
> We are actually working on improving documentation and sample app so any feedback is more than welcomed.
> Offix is used in https://github.com/aerogear/ionic-showcase.
> 
> Demo video: https://www.youtube.com/embed/CrYinCtTHds

**Comment by Hasan-git** [comment]
how to add links and configure inMemoryCache ( cacheRedirects and dataIdFromObject ).

![image](https://user-images.githubusercontent.com/8820596/60097179-8888de00-975b-11e9-945d-60ffcab3f7ac.png)

**Comment by wtrocki** [comment]
So currently we creating a client for developers. Adding links is possible only by overriding the init method of the ApolloClient. However, we are hoping to extract links in the coming week so it will be available to be used with existing clients.

**Comment by Hasan-git** [comment]
![image](https://user-images.githubusercontent.com/8820596/60182266-b0944200-982c-11e9-9bc6-26690f778b72.png)

the Query "allTasks"  accepts argument ( first : Int ) imagine we are providing this query with arg.

@ ROOT_QUERY

- allTasks({ "first" : 1 })
- allTasks({ "first" : 2 })
- ...

how this could updateQuery handle this situation.

Where, in my case I am using pagination with arguments (filter, limit, page, sortBy, direction) then the queries should be invalid and out of date. But, in case the application is offline it should be able to resolve the query from store !? 

I was thinking about invalidating the related queries, then any new request will pass through InMemoryCache "cacheRedirects" where I can get all items from store, but the issue that I should loop over the whole cache to get the stored items by typename and then be able to resolve the data and build the query according to query arguments. but looping over the whole cache is not ideal and will cause performance drawbacks when the cache is big.

**Comment by wtrocki** [comment]
> In my case I am using pagination with arguments (filter, limit, page, sortBy, direction) then the queries should be invalid and out of date. But, in case the application is offline it should be able to resolve the query from the store !?

I think we need to have another issue (this one is about documentation) where we will ask for the team to provide support for pagination which is actually really tricky to get now and it will require some heavy lifting on the developer side. 
We had some use cases for Pagination but they were always business case specific. 

I think for we need to have separate cache update helper for pagination and document pagination case separately. This is something that definitely is in our roadmap. 

Do you mind creating a separate issue for that so we can address those issues faster?

**Comment by wtrocki** [comment]
To implement that:
I will use cacheRedirects: 
Operate on the root object and ignoring the pages. 
Have some simplified equivalent of the pagination.

Pagination is tricky and since there could be many business requirements to do it. It is hard to do it on a generic level. However, we can try to provide some helpers that will assume some format of pagination that should work for the cases where users can adjust their API to accept it.

**Comment by darahayes** [comment]
@Hasan-git since the [0.9.0 release](https://github.com/aerogear/offix/releases/tag/0.9.0) it's now possible to directly pass in your own `InMemoryCache` instance into `OfflineClient`.

```js
const cache = new InMemoryCache();

const offlineClient = new OfflineClient({
  httpUrl: https://example.com/grapqhl,
  cache
});
```

We haven't got many test cases around how OfflineClient will behave using different cache instances with custom configs. If you could try that out and let us know how it works for you that would be great. If you have specific use cases and configurations in mind we could work to get some tests covering those.

**Comment by wtrocki** [comment]
Also worth note that we going to integrate with the Apollo 3.0  in upcoming releases that address pagination issues.

**Comment by darahayes** [comment]
Closing this for now as it's possible to create and configure your own cache instance. Feel free to reopen if needed.
