### ISSUE TITLE
Predicate to SQL statement mapper

### ISSUE THREAD

**Issue by kingsleyzissou** [aerogear/offix#697]
## Feature Request
We need a way to map the various predicates and their operators to SQL statements. It doesn't make sense to fetch everything from a store and then filter them based on the predicate when we could construct the necessary sql statement in the first place (for the sqlite adapter).

**Comment by wtrocki** [comment]
Done by @Eunovo. Anything left? Needs to be fixed? Let's create follow up issue if needed.
