### ISSUE TITLE
Filter Specification

### ISSUE THREAD

**Issue by Eunovo** [aerogear/offix#698]
```
interface Filter {
    [fieldName]: {
        [operatorName]: [value],
        [operatorName]: [value]
    },
   ...,
   or: [Filter],
   and: [Filter],
   not: Filter
}
```

This is the new filter format. To make things easier, users are can easily check for equality without specifying the operation like this
```
{
    clickCount: 5
}
```

This means to get all objects where `clickCount` is 5. The full version is this

```
{
    clickCount: { eq: 5 }
}
```

Also worthy of note is that `{ clickCount: { lt: 5, gt: 0 } }` is  equivalent to `{ clickCount: { lt: 5 }, clickCount: { gt: 0 } }`

CC @kingsleyzissou @wtrocki

**Comment by wtrocki** [comment]
Sounds like amazing API for me!

**Comment by wtrocki** [comment]
I would prefer equality to be exception (you can pass object as filter and this will make assumptions:

All fields in objects are bound by `and` 
All fields represent equality.

For anything else it is best to go with simplified mongo like API/Mango queries to 
avoid interpretation issues.

This means


However with multiple arguments 
```js
{
    or { 
       clickCount: { eq: 5 }, 
       clickCount: { lt: 5 } 
    }
}
```

```js
{
    and { 
       clickCount: { eq: 5 }, 
       clickCount: { lt: 5 } 
    }
}
```

**Comment by wtrocki** [comment]
Made small changes

**Comment by wtrocki** [comment]
Awesome discussion. This was implemented. Closing
