### ISSUE TITLE
OfflineApolloClient crashes during construction as part of Next.JS SSR

### ISSUE THREAD

**Issue by sc0ttdav3y** [aerogear/offix#709]
## Bug Report

* **Affected Package(s)**: offix-client
* **Package version(s)**: 0.15.5
* **Platform (e.g. Android/iOS)**: Web (Next.JS)
* **Platform Version**: Latest Chrome 84
* **Cordova Version**: N/A
* **Node.js / npm versions**: node: 14.4, npm: 6.124.7

**Details**

Hi everyone, and thanks for this project. It looks promising.

I'm building a React web application using Next.JS.  Next.JS provides SSR, and at present it appears offix expects to only run in an environment with a `window` object, so cannot be instantiated.

**Steps to reproduce**

Create a basic client as follows. It doesn't matter which link or cache you add.

```
import {ApolloOfflineClient} from "offix-client";
const client = new ApolloOfflineClient({
    link: new ApolloLink(),
    cache: new InMemoryCache(),
});

```

Now run that in Node (or put this into a basic Next.JS page and call it from its URL to activate server-side rendering of the component).

**Actual behaviour**

When run via Node.JS we get the following crash:

```
ReferenceError: window is not defined
    at Object.exports.isMobileCordova (./node_modules/offix-scheduler/dist/utils/platform.js:13:5)
    at new OffixConfig (./node_modules/offix-scheduler/dist/config/OffixConfig.js:19:46)
    at new OffixScheduler (./node_modules/offix-scheduler/dist/OffixScheduler.js:65:23)
    at new ApolloOfflineClient (./node_modules/offix-client/dist/ApolloOfflineClient.js:90:27)
    at eval (webpack-internal:///./src/components/apollo/client.tsx:79:24)
    at Module../src/components/apollo/client.tsx (./.next/server/static/development/pages/_app.js:302:1)
```

This is because Node.JS does not have a `window` object. 

 **Expected behaviour**

isMobileCordova should have a guard against a missing `window` object and return false.  I don't need offline support of Apollo on the server, but I do want my Next.JS app to route and not crash. Having the Apollo Client get created without persistence would be fine.

**Comment by wtrocki** [comment]
see https://github.com/aerogear/offix/issues/446

**Comment by sc0ttdav3y** [comment]
Thanks for the fast response. I see I'm not alone ;-)

I didn't find that issue in my search, but I've got some workarounds in place similar to what it suggests. It still burned a bunch of hours and I almost gave up.

Perhaps you could add a simple one-liner `typeOf window === "undefined"` check somewhere high up, perhaps in `ApolloOfflineClient`, and point to a doc explaining how to implement an SSR workaround. 

Thanks again.
