### ISSUE TITLE
Custom cache update functions

### ISSUE THREAD

**Issue by Hasan-git** [aerogear/offix#71]
Using apollo client mutation I was able to use update method to provide my custom function to update cache. Thanks for "mutationCacheUpdates" by offix that handle the standard situations.
Whereas , in many cases the data could be nested or overlapped, where some other updates cache should be performed on developer side. 

In this example below, PateintsMediaFile will contain some MediaFiles (overlap), Whenever a new MediaFile is created  PateintsMediaFile should be updated and recalculate some values manually.

![Untitled](https://user-images.githubusercontent.com/8820596/60265550-a9356d00-98ee-11e9-9146-d77feff9b723.png)

And other cases could be nested data , also should update the cache manually.

**Comment by wtrocki** [comment]
@Hasan-git mutationCacheUpdates is just helper that provides value to the mutation update method. So if you have any custom cases we can still provide generic update method and reuse helper inside it to cover standard case if needed.

However, if you think that there will be a generic use case we can add to helpers please let us know.

**Comment by wtrocki** [comment]
ping @StephenCoady @darahayes

**Comment by Hasan-git** [comment]
I think for now just the custom function is real need in common cases

**Comment by Hasan-git** [comment]
Is it possible to add this issue to 0.7.0 milestone ? I think its essential need for anyone to move on to use offix

**Comment by wtrocki** [comment]
Added.
What you mean by:

> I think for now just the custom function is a real need in common cases

It is possible to provide custom function instead of helper by using the `update` field explicitly from `client.mutate` and `client.offlineMutation`.

**Comment by Hasan-git** [comment]
Sorry for misunderstanding, I was asking to provide custom function like => 

![image](https://user-images.githubusercontent.com/8820596/60623518-8540c280-9deb-11e9-9936-d0381988d14b.png)
Anyway, gladly it works and every thing is ok.

##

But, I'm still figuring a way to provide custom function to update cache in offllineMutation(), something like=>

![image](https://user-images.githubusercontent.com/8820596/60623942-b077e180-9dec-11e9-9208-77bfdf21dd2b.png)

**Comment by Hasan-git** [comment]
Any movements ?

**Comment by wtrocki** [comment]
Optimistic response will work however there could be some issue with the typings. 
We are working on rebuilding our entire cache layer that will also include optimistic responses.
I will post more information soon.

To resolve these specific issues please use `as any` for update function and this could work.

**Comment by wtrocki** [comment]
We provide the ability to provide custom cache updates. 
Thank you for logging issue
