### ISSUE TITLE
No Angular/Ionic-Support anymore?

### ISSUE THREAD

**Issue by baststar** [aerogear/offix#711]
I noticed that aerogear/ionic-showcase was deleted.

I can't get together an working example with latest package-versions, i.e. 
@apollo/client 3.1.3
apollo-angular 2.0.3
apollo-angular-link-http 1.10.0
apollo-cache-inmemory 1.6.6
apollo-cache-persist-dev: 0.2.1
apollo-client: 2.6.0
apollo-link: 1.2.11
offix-angular: 0.0.3
offix-client: 0.15.5
offix-client-boost: 0.15.5
graphql 15.0.0
graphql-request: 3.0.0

**Comment by wtrocki** [comment]
We are working on supporting Apollo 3.0 (which has couple problems)
As for angular it should be really easy to get that running as offx-client offflineMutate method can be called in service etc.

As for example see: https://github.com/aerogear/datasync-starter/tree/0.11.0

Although packages might be outdated there.

**Comment by kingsleyzissou** [comment]
Hi @baststar, we have made the decision to move away from the Apollo client and we have decided to deprecate our Offix packages and release our Datastore. I will be closing this issue, but if you have any questions, please feel free to let us know.

You can see the docs for the updated datastore here:
https://offix.dev/docs/getting-started
