### ISSUE TITLE
How I got an optimistic UI working

### ISSUE THREAD

**Issue by sc0ttdav3y** [aerogear/offix#715]
## Guidance / Documentation

Affected Package(s): offix-client
Package version(s): 0.15.5
Platform (e.g. Android/iOS): Web (Next.JS)
Platform Version: Latest Chrome 84
Cordova Version: N/A
Node.js / npm versions: node: 14.4, npm: 6.124.7

Hi, first up, thanks for a great project. 

I followed the [the Getting Started docs](https://offix.dev/docs/getting-started) and [the React Platform Guide docs](https://offix.dev/docs/react), and I had early success but had a bunch of difficulty getting an optimistic UI working, so I'd like to share my experiences to help others, plus get some feedback on my approach.

With not too much effort, I was able to get to this point:

- I got data flowing in from the server (AWS AppSync). 
- I could see it was being stored offline in indexedDB.
- It worked online and offline.
- Mutating data online altered the UI data once the response was returned.
- However, when I mutated data offline, the UI only updated once it syncs when I go online. 

So it's a great start. But I didn't get an optimistic UI.

### Background on the GraphQL model

Understanding my model was crucial to getting optimistic UI working. The key issue was that I have differences between my mutation input, my mutation response and my query response.

### My working solution

So what worked for me is this:

1. A client config using the boost configuration, set up like the React example
2. Explicitly setting up an optimisticResponse
3. Wrangling with the format of the response and input formats for a bit

Here we create a mutation function.

```
    const [updateAsset, {
        error: mutationError,
        loading: isSaving,
    }] = useOfflineMutation(UPDATE_ASSET); 
```

When updating an asset model, I'm doing this:

```
// Here I build the the full item payload.
const mutatedData = {
    ...item,
};
```

My mutation input data is slightly different, so I've got to build a different structure for what I'm submitting to GraphQL.
```
const inputData = {
    id: item.id,
    input: omit(mutatedData, ["id", "__typename"]),
};

```

Next I create an optimistic response. My query result is the mutated data above, but wrapped in an outer array.

```
const optimisticResponse = createOptimisticResponse({
    mutation: UPDATE_ASSET,
    variables: {
        result: "SUCCESS",
        asset: mutatedData,
    },
    operationType: CacheOperation.REFRESH, // this will be ADD or DELETE for those ops.
    returnType: "Asset",
    idField: "id",
});
```

Next I create mutation options. There seems like a lot of overlap between this and the optimisticResponse... I'd love to hear if this is needed, or if there's a more elegant way here.
```
const mutationOptions = createMutationOptions({
    mutation: UPDATE_ASSET,
    // the mutation input
    variables: inputData,

    // which cached queries to update
    updateQuery: [
        {
            query: ASSETS,
        },
    ],
    // keep these the same as optimisticResponse
    operationType: CacheOperation.REFRESH,
    returnType: "Asset",
    idField: "id",
    optimisticResponse,
});
```

Finally, we can call the mutator. The error handling is rough for now.

```
try {
    await updateAsset(mutationOptions);
} catch (error) {
    logger.log(`Error: ${JSON.stringify(error)}`);
    if ("offline" in error && error.offline) {
        logger.log(`Offline sync queued for item ${item.id}`);
        error.watchOfflineChange().then(() => {
            logger.log(`Offline sync completed for item ${item.id}`);
        });
    } else {
        logger.error("Got an error calling updateAsset()");
    }
}
```

This set-up gives me online, offline, optimistic UI.  And it also recovers its offline queued mutations from a refresh, which is cool. I've read that others have had troubles with that. 

### Questions

Now, I'm guessing this isn't the most optimal way to do all this, so I'd love some feedback on my approach.

- First, is this a completely wacky way to do it, or am I on the right track?
- Is an optimistic UI supposed to work for a vanilla getting started / boost configuration approach?
- Is there a better way I should go here?
- What's a good approach to handling mutation errors? I find that if I get a mutation failure at the server, things silently revert to their previous values. 

Ultimately I'd love to know if I'm on the right track here before I push forward with my other models.

### Documentation feedback

Unfortunately the documentation gave me some headaches. It didn't help that I'm relatively new to Apollo as well. 

I know you've got plans to improve this part of the docs, so I hope this write-up helps with that. If I could feel confident I was following best practice, then I could help write some docs.

The Getting Started section doesn't currently have anything on optimistic UI, and I'm honestly not sure if it's supposed to work out of the box or not. It didn't for me of course.

The Offix Cache page makes a good attempt to explain what's needed, but it's not clear whether or not we need to manually set up an optimistic response. What's needed is a conceptual diagram showing how it all fits together. I ended up relying on open and closed issues to get me to the finish line. There, I found lots of support issues saying it's not needed, and the docs itself seems to indicate this is a lower-level thing included in the offline client. 

I think if the getting started section covered a sample for optimistic responses plus some conceptual/architectural overview on it.

Some issues both helped and confused things for me. I was inspired by the fact https://github.com/aerogear/offix/issues/340 worked for the author, but that example didn't work for me. I also saw https://github.com/aerogear/offix/issues/433 and this gave me an example of using an optimistic response.

If you reached the end, then thanks for the project and I hope this helps someone.

Many thanks!

**Comment by kingsleyzissou** [comment]
Hi @sc0ttdav3y, sorry for the delayed response and thanks for the feedback on this and the detailed issue you've submitted. 

So just to clarify, is the optimistic UI working for you with all the steps you have taken?

Some answers to your questions:
1. Typically all the config would not be needed, however, from what I can see in your case, you would have to configure the optimistic responses and mutation functions. The helper functions make an assumption that the variables object is not nested and is a basic object, i.e.: 

```
...
variables: {
    title: 'item title'
 },
...
```

We have built an input mapper that can resolve this somewhat, but based on the example you supplied, it appears that the structure of the variables object is different between the optimistic responses and the mutation options.

2. Yes and no. It works out of the box based on several assumptions, one of this is the structure of the variables being supplied to the mutation function. As soon as the variables are nested, some level of change is needed. For a typical mutation where the variables for the mutation/optimistic response are just a flat object, it will work out of the box.

3. As far as I can see, the steps that you have taken are necessary for your use case.

4. Essentially, we are just listening for errors that are a result of being offline. Graphql or server errors are left up to the developer to decide what to do with the error result. The result is applied as optimistic UI based on the fact that the client is offline. 

Your feedback on the docs is also appreciated. We are in the process of researching a better solution to the offline experience and are looking at ways at how we can bring a generic client into the solution. For the moment, we haven't made too many changes to the current core, but we are actively developing a datastore solution as an alternative to the cache layer. 

The docs are somewhat confusing and out of date. You are correct in that for the most part this is not needed and it is lower-level and part of the offix client, however in your case, for the reasons mentioned before, it is actually necessary.

Hope that clears up some of your questions.
