### ISSUE TITLE
Is there a way to use this library with react class components?

### ISSUE THREAD

**Issue by johhansantana** [aerogear/offix#720]
Hello, I was wondering if this could be possible given that the new trend is using hooks?

**Comment by wtrocki** [comment]
Hi

Do you mean Query and Mutation HOC components? 
Our sample app shows how do obtain direct access to the client. As for HOC support you will be using Query as normal but for the offlineMutate we need to call this directly from js/hook

**Comment by johhansantana** [comment]
Oh, I see. The workaround that we did was just that.

We created a functional component for basically the submit button which we then can use the `useOfflineMutation` from offix.

Thanks!
