### ISSUE TITLE
Update cache after delete mutation

### ISSUE THREAD

**Issue by Hasan-git** [aerogear/offix#73]
How its possible to update the cache after delete mutation?

![Untitled](https://user-images.githubusercontent.com/8820596/60363079-3c53cd00-99eb-11e9-99a0-262b1b2a8d36.png)

![image](https://user-images.githubusercontent.com/8820596/60363058-2b0ac080-99eb-11e9-98c8-3f5402cf730d.png)

**Repo**
I do not know if I'm doing this right. 
But, I have already created very simple demo to play with offix until I feel ready to move for production.
It is a pleasure if you check it [Offix-angular-demo](https://github.com/Hasan-git/offix-angular-demo).

**Comment by Hasan-git** [comment]
Solved, I was following the [ionic-showcase](https://github.com/aerogear/ionic-showcase.) sample, where deleteTask is returning the id of the deleted task rather than the Task.

**Comment by Hasan-git** [comment]
I think it would be better to delete the item from store too. maybe its optional but anyway I would recommend to clean my store

**Comment by wtrocki** [comment]
This a common problem of Apollo InMemory cache. Root items cannot be removed from the cache without hack. The current hack that is InMemoryCache specific.

Our next release will cover that aspect properly. 

For the moment there are two ways to do that in cacheUpdates:

```

```
const context = operation.getContext();
    if (context.cache && context.cache.data) {
      const cacheData = context.cache.data.data;
      const idKey = context.getCacheKey({ __typename: context.returnType, id });
      delete cacheData[idKey];
	  context.cache.write(
}

**Comment by wtrocki** [comment]
che

**Comment by wtrocki** [comment]
> But, I have already created very simple demo to play with offix until I feel ready to move for production. It is a pleasure if you check it Offix-angular-demo.

I love it. Do you mind if we extend it a little bit more and bring into AeroGear org! Thank you so much for all the hard work you are putting to help us to move out the beta stage! I really appreciate that.

**Comment by Hasan-git** [comment]
> Do you mind if we extend it a little bit more and bring into AeroGear org.

My pleasure.

> Thank you so much for all the hard work you are putting to help us to move out the beta stage! I really appreciate that.

Offix success means a lot to us.

**Comment by wtrocki** [comment]
We now provide helper for delete opration that can be used for this use case.
In near future we going to provide alternative to cache helpers that will support deletion out of the box.
