### ISSUE TITLE
Query by ID support for query hooks

### ISSUE THREAD

**Issue by Eunovo** [aerogear/offix#730]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Our current query hooks do not support queryById

**Describe the solution you'd like**
A way for user to be able query by id using hooks

Options we have right now;
- Seperate hooks for queryById
- Update current query hooks to also support queryById

CC @wtrocki  @kingsleyzissou

**Comment by wtrocki** [comment]
Lets update current query hooks. I like firebase approach that allows you to  filter.
Something like `filter: Filter, key: String`

**Comment by Eunovo** [comment]
I would like to avoid creating extra hooks so I'm leaning toward 

> * Update current query hooks to also support queryById

To do this we need to accept both filter and id. 

If we update the parameters to `filter?: Filter, key?: string`, the user would have to do something like this `query(null, documentId)` to perform a query by id operation.

If we update the parameters to `selector?: Filter | string` where selector could be a filter, key or undefined, the user would do something like this `query(documentId)` or `query(filter)` or `query()` to perform a query by id or query by filter or query all operation.

There's an argument that using `selector?: Filter | string` could be confusing, I don't think it's more confusing than having to explain what this `query(filter, key)`(here, both the filter and key are set) will return.

Which approach do you think is better? @wtrocki  @kingsleyzissou

**Comment by wtrocki** [comment]
> There's an argument that using selector?: Filter | string could be confusing, I don't think it's more confusing than having to explain what this query(filter, key)(here, both the filter and key are set) will return.

Ok. Let's go with it then. If this will be confusing we can always introduce another param without issues.

**Comment by Eunovo** [comment]
This was implemented in #735
