### ISSUE TITLE
Bug: id.startsWith is not a function

### ISSUE THREAD

**Issue by Hasan-git** [aerogear/offix#74]
![image](https://user-images.githubusercontent.com/8820596/60386212-eb031680-9a9a-11e9-9b2c-d3890f489c67.png)

**Comment by wtrocki** [comment]
This is happening when the model is missing `id` field or id field is not a string
@Hasan-git I will quickly patch it as this looks like a blocker for me.

I think we have 2 issues here. The first one is that we always assume `id` is a string and this is a critical issue that I will patch today or tomorrow.

The second one will be the fact that we ignore `MutationHelperOptions.idFIeld` provided by the user and use the hardcoded id in `IDProcessor` - Going to create a separate issue for that bug.

Can you provide me a value of the id field that is triggering this issue to make sure that my fix is going to address it?

To fix this bug we need:
- Make additional check for id and transform it to string
- Document the MutationHelperOptions.idFIeld for customization needs

**Comment by Hasan-git** [comment]
> Can you provide me a value of the id field that is triggering this issue to make sure that my fix is going to address it?

Indeed, the whole object was null. if its does matter that I was doing a mutation that should return an GraphqlError but I didn't ,  maybe if I was returning an GraphqlError this bug will not be catched

**Comment by wtrocki** [comment]
@Hasan-git This makes sense now. Going to patch this and do new patch release.

**Comment by wtrocki** [comment]
Done. Going to release 0.6.1
