### ISSUE TITLE
Use auto generated id variable in optimistic response rather than Client:xxxxx

### ISSUE THREAD

**Issue by Hasan-git** [aerogear/offix#75]
Is it possible to use the variable id (which is auto-generated on client-side) in optimistic response rather than "client:xxxxxx".

In case of nested data, this approach will cause an issues. Then, my solution is always to generate an id on client side and offix should accept this variable.

![image](https://user-images.githubusercontent.com/8820596/60388132-d2542a00-9ab5-11e9-8a4c-a29627ea0d5d.png)

**Comment by wtrocki** [comment]
I love this idea! Really really useful feedback.
We needed to have a unified way to know if the id we dealing with is autogenerated. 
We execute id mapping after based on that. 

Does having `client:Greeting:xxxxxx` will resolve this problem?
If yes then this is very trivial fix. In fact we do not need function - we have access to typename so our id should be:

`client:{TypeName}:{generatedId}`

WDYT?

**Comment by Hasan-git** [comment]
> Does having client:Greeting:xxxxxx will resolve this problem?

Of course no, greeing.id should be the id set by variables.id ,,, this fixes the issue

**Reproduce** 

Assume that we have the below scenario (it's a real scenario) .

STEP 1 create a **location** while offline:

```
      location: {
        id: "client:0dh0M5MW",
        name: "Saint George",
        contact: ""
      }
```

STEP 2 creating a **condition** while offline

```
      condition: {
        id: "WHAT EVER",
        location: {
          id: "client:0dh0M5MW", //  <--- relation, the server expects GUID or ObjectId.... throw an error
          name: "Saint George",
        },
        medications: [],
        opened: "2019-05-09"
        .....
      }
```

Currently, I'm using mongodb which uses ObjectId as default primary key.... .
The idea , when creating any new item I'am always providing item id (ObjectId) on client side, then I'm able to use items freely while offline and when going online the server will save the data with there generated ids (by client).

So, I'm expecting item object should be stored as => 

```
Location:5d19ebc00bc49edf8ffad966 {
    id : "5d19ebc00bc49edf8ffad966 ",  < --- 
    name: "Saint George"
}
```
id is equivalent to variables.id

rather than 

```
Client:XdhXM5XX {
    id : "Client:XdhXM5XX ", <---
    name: "Saint George"
}
```

**Comment by wtrocki** [comment]
Awesome. 

> Of course no, greeing.id should be the id set by variables.id ,,, this fixes the issue

Yes. Now I fully understand what we mean here. Yes. We should resolve this problem

**Comment by wtrocki** [comment]
Passing Id is now possible thru the client (both by data or using your own optimistic response creator. Closing
