### ISSUE TITLE
DataStore encryption

### ISSUE THREAD

**Issue by kingsleyzissou** [aerogear/offix#750]
## Feature Request

Currently everything in the datastore is stored in plaintext.  The ModelSchema could potentially be responsible for field level encryption. I have added some initial support in the schema to extract encrypted fields, but there is no implementation yet for actually encrypting them.

**Comment by wtrocki** [comment]
I think we need encryption done in the way to ensure security as whole. Encrypying single field will be ineffective in terms of performance and require in house implementation. 
WHen using Encryption wrappers for IDB and SQLLite we can provide end to end encryption with mechanism of underlying operating system (mobile) thus not affecting js engine performance

**Comment by wtrocki** [comment]
For 1.0 I see people bringing their own preferred library as wrapper for storage. We can provide that feature if we get enterprise support for offix (probably not)
