### ISSUE TITLE
[datastore sqlite] meta_query_info table is not being created

### ISSUE THREAD

**Issue by kingsleyzissou** [aerogear/offix#772]
## Bug Report

The detlasync is failing as the `meta_query_info table` is not being created. This is not the easiest fix either because we need to know the all the storenames before this table is created so we can create a column for each.

**Comment by wtrocki** [comment]
There are changes in the sqllite provided that I have done/needs to be finished. 
This is no longer actual (althjogh outher issues persist :) )
