### ISSUE TITLE
[datasync sqlite] metadata serialization is causing issues

### ISSUE THREAD

**Issue by kingsleyzissou** [aerogear/offix#773]
## Bug Report

Metadata queue items need to be serialized before they can be saved to an sqlite table. There are some issues with this and the saveAndUpdate function is not behaving as expected. This results in a `unique key constraint` error which breaks everything on the app and we get an endless loops of errors as the replicator gets stuck in a cycle.

**Comment by wtrocki** [comment]
I have a rewritten the queue. There is no more save and update.
