### ISSUE TITLE
Migrate from mocha to ava with better test coverage

### ISSUE THREAD

**Issue by darahayes** [aerogear/offix#78]
We're making some really great progress with Offix, however I think some work needs to be done around testing. I'd like this issue to focus solely on **unit tests**. There is plenty of scope for integration tests also, but I think we can start simple and cover those in a separate issue.

There are several components in Offix that perform some complex and tricky logic. Cache operations, data structure manipulations. Let's try to collaborate and identify the areas where we will get the most value out of unit tests.

I see this initiative being tackled as lots of small PRs. Contributions in the form of PRs, and suggestions/discussion are welcome. Myself and other collaborators are here to help!

**Comment by wtrocki** [comment]
@darahayes This aged badly. How about we will use jest for both integration and unit tests. 
Unit tests now could be much easier but we still need to have integration tests focused testing due to the complexity of the flow.

**Comment by darahayes** [comment]
Closing in favour of https://github.com/aerogear/offix/issues/192
