### ISSUE TITLE
Create,Delete, Update doesn't need loading, error or data returned from hook. 

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#873]
## Feature Request

Save method can actually return promise to handle those.

**Comment by Eunovo** [comment]
@wtrocki The save method returning a promise is a good idea. It allows users to await the operation and execute some commands when complete. I have used this approach before. But the `loading` indicator is still useful because without it, users would have to create their own loading states.

**Comment by wtrocki** [comment]
So there is actual hook and then actual method that is being called to create things. It has things returned twice.. SOrry for not being clear.

**Comment by Eunovo** [comment]
@wtrocki  Let me share examples to illustrate what I mean.

Here is the `useSave` hook with loading and error states
```
const { loading, error, save } = useSave(model);

const onSubmit = async () => {
    try {
        await save(data);
        // trigger success popup
    } catch (e) {
         // trigger error popup
    }
}
 
return <div>
    {error && <div>{error.message}</div>}

    .....<your form here>

    <button>
        Save { loading && <div>A loading indicator here or wherever you want</div> }
    </button>
</div>
```

Now, here is the `useSave` hook without loading and error states
```
const [loading, setLoading] = useState(false);
const [error, setError] = useState(null);
const { save } = useSave(model);

const onSubmit = async () => {
    if (loading) return;
    try {
        setLoading(true);
        await save(data);
        // trigger success popup
    } catch (e) {
         // trigger error popup
        setError(e);
    } finally { setLoading(false); }
}
 
// ... same as the previous example
```

As you can see in the second example, users have to manage loading and error states themselves if the loading and error states are taken out from the hooks.

**Comment by wtrocki** [comment]
I meant that save method itself should probably return void?

**Comment by Eunovo** [comment]
The promise returned from `save`  is still useful. In my example, I `await` that promise and trigger popups.
