### ISSUE TITLE
Rename isLoading to loading in offix-datastore hooks

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#874]
## Feature Request

See https://github.com/aerogear/offix/blob/master/packages/datastore/datastore/src/react/hooks/query.ts#L86

**Comment by wtrocki** [comment]
Similar can happen with `subscribeToMore` => `subscribeToUpdates`

**Comment by wtrocki** [comment]
CC @kingsleyzissou

**Comment by mariandaniel24** [comment]
May I work on this ?

**Comment by kingsleyzissou** [comment]
@mariandaniel24 fire away
