### ISSUE TITLE
Client.mutate should not include any offline and conflict links

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix#89]
We need to make sure that we have a differentiation between oflineMutate and mutation. We have onlineOnly but since we dropping now support for client.mutate() we can think about disabling all functionalities when client.mutate is used.

**Comment by wtrocki** [comment]
@darahayes Closing as outdated. We going to document that.

**Comment by darahayes** [comment]
@wtrocki I'm going to reopen this for the time being and I'll close that once #170  is merged. Otherwise I'll forget to add this to the release notes 😄

**Comment by darahayes** [comment]
Closing this now as #170 is merged.
