### ISSUE TITLE
Please export ApolloQueryResult from offix

### ISSUE THREAD

**Issue by cjohn001** [aerogear/offix#896]
Hello together,
I am using offix-client as the engine below the offix-angular (https://github.com/cjohn001/offix-angular) glue layer for angular development, and I would like to get rid of direct dependencies to apollo-client. I would be able in doing so if ApolloQueryResult would be exported from offix-client. Could you maybe add this to the 0.15.x series?

**Comment by wtrocki** [comment]
Sounds like good idea. Added as hacktoberfest as it is quite simple fix. `ApolloQueryResult` comes from apollo library and needs to be exported in index.ts

**Comment by kingsleyzissou** [comment]
Fixed in #1006
