### ISSUE TITLE
Getting error while build project 

### ISSUE THREAD

**Issue by jatravi38** [aerogear/offix#901]
## Bug Report
I am try to use this library in my demo project but when i rebuild project get below error .Please can you help me how to fix that.

 Task :offix:kaptDebugKotlin FAILED
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Database.java:6: error: incompatible types: NonExistentClass cannot be converted to Annotation
**@error.NonExistentClass()**
      ^
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Database.java:7: error: incompatible types: Database cannot be converted to Annotation
@Database()
 ^
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/MutationDao.java:6: error: incompatible types: NonExistentClass cannot be converted to Annotation
@error.NonExistentClass()
      ^
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Mutation.java:6: error: incompatible types: NonExistentClass cannot be converted to Annotation
@error.NonExistentClass()
      ^
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/MutationDao.java:9: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/MutationDao.java:13: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/MutationDao.java:18: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/MutationDao.java:22: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/MutationDao.java:25: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/MutationDao.java:28: error: incompatible types: NonExistentClass cannot be converted to Annotation
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Database.java:6: error: incompatible types: NonExistentClass cannot be converted to Annotation
@error.NonExistentClass()
      ^

    @error.NonExistentClass()
          ^
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Mutation.java:77: error: incompatible types: NonExistentClass cannot be converted to Annotation
    java.lang.String responseClassName, @error.NonExistentClass()
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Database.java:7: error: incompatible types: Database cannot be converted to Annotation
@Database()
 ^

e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/MutationDao.java:6: error: incompatible types: NonExistentClass cannot be converted to Annotation
@error.NonExistentClass()
      ^

                                              ^
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Mutation.java:117: error: incompatible types: NonExistentClass cannot be converted to Annotation
    java.lang.String responseClassName, @error.NonExistentClass()
                                              ^
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Converters.java:9: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Mutation.java:6: error: incompatible types: NonExistentClass cannot be converted to Annotation
@error.NonExistentClass()
      ^

          ^
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/MutationDao.java:9: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^

e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Converters.java:16: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/MutationDao.java:13: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^

e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Converters.java:23: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^
e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Converters.java:30: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^
w: [kapt] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: androidx.room.RoomProcessor (NON_INCREMENTAL).

e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/MutationDao.java:18: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^

e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/MutationDao.java:22: error: incompatible types: NonExistentClass cannot be converted to Annotation
    **@error.NonExistentClass()**
          ^

e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/MutationDao.java:25: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^

e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/MutationDao.java:28: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^

e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Mutation.java:77: error: incompatible types: NonExistentClass cannot be converted to Annotation
    java.lang.String responseClassName, @error.NonExistentClass()
                                              ^

e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Mutation.java:117: error: incompatible types: NonExistentClass cannot be converted to Annotation
    java.lang.String responseClassName, @error.NonExistentClass()
                                              ^

e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Converters.java:9: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^

e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Converters.java:16: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^

e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Converters.java:23: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^

e: /Users/avi/Downloads/Ravi Project/flutter/OffixAndroid/offix/build/tmp/kapt3/stubs/debug/org/aerogear/offix/persistence/Converters.java:30: error: incompatible types: NonExistentClass cannot be converted to Annotation
    @error.NonExistentClass()
          ^

w: [kapt] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: androidx.room.RoomProcessor (NON_INCREMENTAL).

* **Platform : Android**:
* **Platform Version : 28,29 (APi version) and android studio 4.0.1 **:
* **Node.js / npm versions : 6.14.0**:

i am not adding any other library and use same sample code that provided in below link 
https://github.com/aerogear/offix-android/tree/master/sample

also i am not understand what is the use of sever folder please help me to fix this issue so i can use that.

**Comment by kingsleyzissou** [comment]
Hi @jatravi38, apologies for the late reply. That offix-android repo is not the most up-to-date version of the app and is actually quite far behind. I don't think we will be updating it either. You can have a look at some of the examples in the Offix repo, we have done an example in React Native. 

Otherwise. we have built a version using Ionic Capcitor in our [AeroGear Datasync starter](https://github.com/aerogear/datasync-starter) application that you can try out.
