### ISSUE TITLE
0.7.0 release?

### ISSUE THREAD

**Issue by mgobins** [aerogear/offix#93]
When we can expect 0.7.0 release? 
Can you do fix to support for Apollo 2.6 - types are breaking now.
I like more examples for conflict with actual database and react integration. 
It is hard to use it in React. Do you plan to provide offix components?

**Comment by wtrocki** [comment]
We have an issue for Apollo 2.6 support #81 
We do not have db example in offix but you might also find a good example in:
https://github.com/aerogear/ionic-showcase . We are still working on adjusting the changes to the new API.

As for react components - do you mean something like <OfflineMutation>

**Comment by wtrocki** [comment]
The release has done! We are working on 0.8.0
