### ISSUE TITLE
rxDB integration / offix Limitations

### ISSUE THREAD

**Issue by MentalGear** [aerogear/offix#995]
First off: thank you for this library and the Ionic integrations (maybe soon vue? 👍 ) !
I'm planning to use offix with rxdb (realtime offline db). Has anyone had expierence with integrating both, or is there a feature overlap ?
https://github.com/pubkey/rxdb

Also, I would be interested to know more about how capable the offix's offline storage is? For what amount of data can it be used and is it a good fit for apps that may not come back online for weeks? It would be helpful to have a Limitations Page in the docs that could clearify these points and have them ready for reference for developers.

**Comment by wtrocki** [comment]
We are building similar project to rxdb but it is still in early phase. Generally I think using RxDB will mean that we do not need offix as having both stores will make things very difficult.

**Comment by MentalGear** [comment]
Thanks for your reply @wtrocki !
Looking forward for the documentation on usage limitation.
Do you think it would be possible to use only offix's graphQL conflict resolution code with rxDB ? (rxDB on graphQL doesn't provide any conflict resolution code)

**Comment by wtrocki** [comment]
RXdb does allow one to handle conflicts - probably not documented as entire project is just thin wrapper. Conflicts usually should be happening on the server side. Check https://graphback.dev/docs/datasync/conflict-resolution-intro on how this can work

**Comment by kingsleyzissou** [comment]
Hey @MentalGear, we have now released our Offix Datastore, which is our version of a client-side database. It has support for replication to a Graphback backend or any backend that follows the [GraphQL Crud specification](https://graphqlcrud.org/).

You can check out the docs here:
https://offix.dev/docs/getting-started

**Comment by MentalGear** [comment]
Thanks guys for your work, very interesting indeed !

**Comment by MentalGear** [comment]
I find it confusing that the new version of offix is apparently called datastore. Espeically in the docs menu, there's a dropdown with items stating: "datastore" and "offix". In the beginning, I thought datastore was simply an opt-in feature for offix. Just maybe something you want to clarify.

**Comment by wtrocki** [comment]
Thank you for feedback. 
DataStore is our way to provide great user experience and provide proper maintenance without depending on thrid party library (Apollo). 

Datastore can use Apollo, Urql etc.
Offix could not move to Apollo 3.0 because of some limitations and we personally stopped working with Apollo client thus did not had any future for us to maintain library that we not going to use.

As for the docs - We wanted to still keep old offix docs for people who still use it.

**Comment by MentalGear** [comment]
Thanks for the reply. Do I understand right that DataStore is a new project, and not a continuation of Offix?
Will it be hosted at a different location, or will Offix repo and website just be renamed to DataStore ?

**Comment by wtrocki** [comment]
The whole project is called OffixDatastore. It uses essential elements from the offix 0.15 etc. 
Offix based on Apollo will be discontinued. @kingsleyzissou will share blog post with all explanations
